


CREATE TABLE IF NOT EXISTS shopizer."category" (
  "CATEGORY_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "CATEGORY_IMAGE" varchar(100) DEFAULT NULL,
  "CATEGORY_STATUS" bit(1) DEFAULT NULL,
  "CODE" varchar(100) NOT NULL,
  "DEPTH" integer DEFAULT NULL,
  "FEATURED" bit(1) DEFAULT NULL,
  "LINEAGE" varchar(255) DEFAULT NULL,
  "SORT_ORDER" integer DEFAULT NULL,
  "VISIBLE" bit(1) DEFAULT NULL,
  "MERCHANT_ID" integer NOT NULL,
  "PARENT_ID" bigint DEFAULT NULL,
  PRIMARY KEY (CATEGORY_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."category_description" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "CATEGORY_HIGHLIGHT" varchar(255) DEFAULT NULL,
  "META_DESCRIPTION" varchar(255) DEFAULT NULL,
  "META_KEYWORDS" varchar(255) DEFAULT NULL,
  "META_TITLE" varchar(120) DEFAULT NULL,
  "SEF_URL" varchar(120) DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "CATEGORY_ID" bigint NOT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."content" (
  "CONTENT_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "CODE" varchar(100) NOT NULL,
  "CONTENT_POSITION" varchar(10) DEFAULT NULL,
  "CONTENT_TYPE" varchar(10) DEFAULT NULL,
  "LINK_TO_MENU" bit(1) DEFAULT NULL,
  "PRODUCT_GROUP" varchar(255) DEFAULT NULL,
  "SORT_ORDER" integer DEFAULT NULL,
  "VISIBLE" bit(1) DEFAULT NULL,
  "MERCHANT_ID" integer NOT NULL,
  PRIMARY KEY (CONTENT_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."content_description" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "META_DESCRIPTION" varchar(255) DEFAULT NULL,
  "META_KEYWORDS" varchar(255) DEFAULT NULL,
  "META_TITLE" varchar(255) DEFAULT NULL,
  "SEF_URL" varchar(120) DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "CONTENT_ID" bigint NOT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."country" (
  "COUNTRY_ID" integer NOT NULL,
  "COUNTRY_ISOCODE" varchar(255) NOT NULL,
  "COUNTRY_SUPPORTED" bit(1) DEFAULT NULL,
  "GEOZONE_ID" bigint DEFAULT NULL,
  PRIMARY KEY (COUNTRY_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."country_description" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "COUNTRY_ID" integer NOT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."currency" (
  "CURRENCY_ID" bigint NOT NULL,
  "CURRENCY_CODE" varchar(255) DEFAULT NULL,
  "CURRENCY_CURRENCY_CODE" varchar(255) NOT NULL,
  "CURRENCY_NAME" varchar(255) DEFAULT NULL,
  "CURRENCY_SUPPORTED" bit(1) DEFAULT NULL,
  PRIMARY KEY (CURRENCY_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."customer" (
  "CUSTOMER_ID" bigint NOT NULL,
  "CUSTOMER_ANONYMOUS" bit(1) DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "BILLING_STREET_ADDRESS" varchar(256) DEFAULT NULL,
  "BILLING_CITY" varchar(100) DEFAULT NULL,
  "BILLING_COMPANY" varchar(100) DEFAULT NULL,
  "BILLING_FIRST_NAME" varchar(64) NOT NULL,
  "BILLING_LAST_NAME" varchar(64) NOT NULL,
  "LATITUDE" varchar(100) DEFAULT NULL,
  "LONGITUDE" varchar(100) DEFAULT NULL,
  "BILLING_POSTCODE" varchar(20) DEFAULT NULL,
  "BILLING_STATE" varchar(100) DEFAULT NULL,
  "BILLING_TELEPHONE" varchar(32) DEFAULT NULL,
  "CUSTOMER_COMPANY" varchar(100) DEFAULT NULL,
  "REVIEW_AVG" decimal(19,2) DEFAULT NULL,
  "REVIEW_COUNT" integer DEFAULT NULL,
  "CUSTOMER_DOB" timestamp DEFAULT NULL,
  "DELIVERY_STREET_ADDRESS" varchar(256) DEFAULT NULL,
  "DELIVERY_CITY" varchar(100) DEFAULT NULL,
  "DELIVERY_COMPANY" varchar(100) DEFAULT NULL,
  "DELIVERY_FIRST_NAME" varchar(64) DEFAULT NULL,
  "DELIVERY_LAST_NAME" varchar(64) DEFAULT NULL,
  "DELIVERY_POSTCODE" varchar(20) DEFAULT NULL,
  "DELIVERY_STATE" varchar(100) DEFAULT NULL,
  "DELIVERY_TELEPHONE" varchar(32) DEFAULT NULL,
  "CUSTOMER_EMAIL_ADDRESS" varchar(96) NOT NULL,
  "CUSTOMER_GENDER" varchar(1) DEFAULT NULL,
  "CUSTOMER_NICK" varchar(96) DEFAULT NULL,
  "CUSTOMER_PASSWORD" varchar(60) DEFAULT NULL,
  "PROVIDER" varchar(255) DEFAULT NULL,
  "BILLING_COUNTRY_ID" integer NOT NULL,
  "BILLING_ZONE_ID" bigint DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "DELIVERY_COUNTRY_ID" integer DEFAULT NULL,
  "DELIVERY_ZONE_ID" bigint DEFAULT NULL,
  "MERCHANT_ID" integer NOT NULL,
  PRIMARY KEY (CUSTOMER_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."customer_attribute" (
  "CUSTOMER_ATTRIBUTE_ID" bigint NOT NULL,
  "CUSTOMER_ATTR_TXT_VAL" varchar(255) DEFAULT NULL,
  "CUSTOMER_ID" bigint NOT NULL,
  "OPTION_ID" bigint NOT NULL,
  "OPTION_VALUE_ID" bigint NOT NULL,
  PRIMARY KEY (CUSTOMER_ATTRIBUTE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."customer_group" (
  "CUSTOMER_ID" bigint NOT NULL,
  "GROUP_ID" integer NOT NULL
);


CREATE TABLE IF NOT EXISTS shopizer."customer_opt_val_description" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "CUSTOMER_OPT_VAL_ID" bigint DEFAULT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."customer_optin" (
  "CUSTOMER_OPTIN_ID" bigint NOT NULL,
  "EMAIL" varchar(255) NOT NULL,
  "FIRST" varchar(255) DEFAULT NULL,
  "LAST" varchar(255) DEFAULT NULL,
  "OPTIN_DATE" timestamp DEFAULT NULL,
  "VALUE" text,
  "MERCHANT_ID" integer NOT NULL,
  "OPTIN_ID" bigint DEFAULT NULL,
  PRIMARY KEY (CUSTOMER_OPTIN_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."customer_option" (
  "CUSTOMER_OPTION_ID" bigint NOT NULL,
  "CUSTOMER_OPT_ACTIVE" bit(1) DEFAULT NULL,
  "CUSTOMER_OPT_CODE" varchar(255) NOT NULL,
  "CUSTOMER_OPTION_TYPE" varchar(10) DEFAULT NULL,
  "CUSTOMER_OPT_PUBLIC" bit(1) DEFAULT NULL,
  "SORT_ORDER" integer DEFAULT NULL,
  "MERCHANT_ID" integer NOT NULL,
  PRIMARY KEY (CUSTOMER_OPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."customer_option_desc" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "CUSTOMER_OPTION_COMMENT" text,
  "LANGUAGE_ID" integer NOT NULL,
  "CUSTOMER_OPTION_ID" bigint NOT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."customer_option_set" (
  "CUSTOMER_OPTIONSET_ID" bigint NOT NULL,
  "SORT_ORDER" integer DEFAULT NULL,
  "CUSTOMER_OPTION_ID" bigint NOT NULL,
  "CUSTOMER_OPTION_VALUE_ID" bigint NOT NULL,
  PRIMARY KEY (CUSTOMER_OPTIONSET_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."customer_option_value" (
  "CUSTOMER_OPTION_VALUE_ID" bigint NOT NULL,
  "CUSTOMER_OPT_VAL_CODE" varchar(255) NOT NULL,
  "CUSTOMER_OPT_VAL_IMAGE" varchar(255) DEFAULT NULL,
  "SORT_ORDER" integer DEFAULT NULL,
  "MERCHANT_ID" integer NOT NULL,
  PRIMARY KEY (CUSTOMER_OPTION_VALUE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."customer_review" (
  "CUSTOMER_REVIEW_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "REVIEW_DATE" timestamp DEFAULT NULL,
  "REVIEWS_RATING" double precision DEFAULT NULL,
  "REVIEWS_READ" bigint DEFAULT NULL,
  "STATUS" integer DEFAULT NULL,
  "CUSTOMERS_ID" bigint DEFAULT NULL,
  "REVIEWED_CUSTOMER_ID" bigint DEFAULT NULL,
  PRIMARY KEY (CUSTOMER_REVIEW_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."customer_review_description" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "CUSTOMER_REVIEW_ID" bigint DEFAULT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."file_history" (
  "FILE_HISTORY_ID" bigint NOT NULL,
  "ACCOUNTED_DATE" timestamp DEFAULT NULL,
  "DATE_ADDED" timestamp NOT NULL,
  "DATE_DELETED" timestamp DEFAULT NULL,
  "DOWNLOAD_COUNT" integer NOT NULL,
  "FILE_ID" bigint DEFAULT NULL,
  "FILESIZE" integer NOT NULL,
  "MERCHANT_ID" integer NOT NULL,
  PRIMARY KEY (FILE_HISTORY_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."geozone" (
  "GEOZONE_ID" bigint NOT NULL,
  "GEOZONE_CODE" varchar(255) DEFAULT NULL,
  "GEOZONE_NAME" varchar(255) DEFAULT NULL,
  PRIMARY KEY (GEOZONE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."geozone_description" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "GEOZONE_ID" bigint DEFAULT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."language" (
  "LANGUAGE_ID" integer NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "CODE" varchar(255) NOT NULL,
  "SORT_ORDER" integer DEFAULT NULL,
  PRIMARY KEY (LANGUAGE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."manufacturer" (
  "MANUFACTURER_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "CODE" varchar(100) NOT NULL,
  "MANUFACTURER_IMAGE" varchar(255) DEFAULT NULL,
  "SORT_ORDER" integer DEFAULT NULL,
  "MERCHANT_ID" integer NOT NULL,
  PRIMARY KEY (MANUFACTURER_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."manufacturer_description" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "DATE_LAST_CLICK" timestamp DEFAULT NULL,
  "MANUFACTURERS_URL" varchar(255) DEFAULT NULL,
  "URL_CLICKED" integer DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "MANUFACTURER_ID" bigint NOT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."merchant_configuration" (
  "MERCHANT_CONFIG_ID" bigint NOT NULL,
  "ACTIVE" bit(1) DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "CONFIG_KEY" varchar(255) DEFAULT NULL,
  "TYPE" varchar(255) DEFAULT NULL,
  "VALUE" text,
  "MERCHANT_ID" integer DEFAULT NULL,
  PRIMARY KEY (MERCHANT_CONFIG_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."merchant_language" (
  "stores_MERCHANT_ID" integer NOT NULL,
  "languages_LANGUAGE_ID" integer NOT NULL
);


CREATE TABLE IF NOT EXISTS shopizer."merchant_log" (
  "MERCHANT_LOG_ID" bigint NOT NULL,
  "LOG" text,
  "MODULE" varchar(25) DEFAULT NULL,
  "MERCHANT_ID" integer NOT NULL,
  PRIMARY KEY (MERCHANT_LOG_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."merchant_store" (
  "MERCHANT_ID" integer NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "STORE_CODE" varchar(100) NOT NULL,
  "CONTINUESHOPPINGURL" varchar(150) DEFAULT NULL,
  "CURRENCY_FORMAT_NATIONAL" bit(1) DEFAULT NULL,
  "DOMAIN_NAME" varchar(80) DEFAULT NULL,
  "IN_BUSINESS_SINCE" date DEFAULT NULL,
  "INVOICE_TEMPLATE" varchar(25) DEFAULT NULL,
  "SEIZEUNITCODE" varchar(5) DEFAULT NULL,
  "STORE_EMAIL" varchar(60) NOT NULL,
  "STORE_LOGO" varchar(100) DEFAULT NULL,
  "STORE_TEMPLATE" varchar(25) DEFAULT NULL,
  "STORE_ADDRESS" varchar(255) DEFAULT NULL,
  "STORE_CITY" varchar(100) NOT NULL,
  "STORE_NAME" varchar(100) NOT NULL,
  "STORE_PHONE" varchar(50) NOT NULL,
  "STORE_POSTAL_CODE" varchar(15) NOT NULL,
  "STORE_STATE_PROV" varchar(100) DEFAULT NULL,
  "USE_CACHE" bit(1) DEFAULT NULL,
  "WEIGHTUNITCODE" varchar(5) DEFAULT NULL,
  "COUNTRY_ID" integer NOT NULL,
  "CURRENCY_ID" bigint NOT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "ZONE_ID" bigint DEFAULT NULL,
  PRIMARY KEY (MERCHANT_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."module_configuration" (
  "MODULE_CONF_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "CODE" varchar(255) NOT NULL,
  "DETAILS" text,
  "CONFIGURATION" text,
  "CUSTOM_IND" bit(1) DEFAULT NULL,
  "IMAGE" varchar(255) DEFAULT NULL,
  "MODULE" varchar(255) DEFAULT NULL,
  "REGIONS" varchar(255) DEFAULT NULL,
  "TYPE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (MODULE_CONF_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."optin" (
  "OPTIN_ID" bigint NOT NULL,
  "CODE" varchar(255) NOT NULL,
  "DESCRIPTION" varchar(255) DEFAULT NULL,
  "END_DATE" timestamp DEFAULT NULL,
  "TYPE" varchar(255) NOT NULL,
  "START_DATE" timestamp DEFAULT NULL,
  "MERCHANT_ID" integer DEFAULT NULL,
  PRIMARY KEY (OPTIN_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."order_account" (
  "ORDER_ACCOUNT_ID" bigint NOT NULL,
  "ORDER_ACCOUNT_BILL_DAY" integer NOT NULL,
  "ORDER_ACCOUNT_END_DATE" date DEFAULT NULL,
  "ORDER_ACCOUNT_START_DATE" date NOT NULL,
  "ORDER_ID" bigint NOT NULL,
  PRIMARY KEY (ORDER_ACCOUNT_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."order_account_product" (
  "ORDER_ACCOUNT_PRODUCT_ID" bigint NOT NULL,
  "ORDER_ACCOUNT_PRODUCT_ACCNT_DT" date DEFAULT NULL,
  "ORDER_ACCOUNT_PRODUCT_END_DT" date DEFAULT NULL,
  "ORDER_ACCOUNT_PRODUCT_EOT" timestamp DEFAULT NULL,
  "ORDER_ACCOUNT_PRODUCT_L_ST_DT" timestamp DEFAULT NULL,
  "ORDER_ACCOUNT_PRODUCT_L_TRX_ST" integer NOT NULL,
  "ORDER_ACCOUNT_PRODUCT_PM_FR_TY" integer NOT NULL,
  "ORDER_ACCOUNT_PRODUCT_ST_DT" date NOT NULL,
  "ORDER_ACCOUNT_PRODUCT_STATUS" integer NOT NULL,
  "ORDER_ACCOUNT_ID" bigint NOT NULL,
  "ORDER_PRODUCT_ID" bigint NOT NULL,
  PRIMARY KEY (ORDER_ACCOUNT_PRODUCT_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."order_attribute" (
  "ORDER_ATTRIBUTE_ID" bigint NOT NULL,
  "IDENTIFIER" varchar(255) NOT NULL,
  "VALUE" varchar(255) NOT NULL,
  "ORDER_ID" bigint NOT NULL,
  PRIMARY KEY (ORDER_ATTRIBUTE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."order_product" (
  "ORDER_PRODUCT_ID" bigint NOT NULL,
  "ONETIME_CHARGE" decimal(19,2) NOT NULL,
  "PRODUCT_NAME" varchar(64) NOT NULL,
  "PRODUCT_QUANTITY" integer DEFAULT NULL,
  "PRODUCT_SKU" varchar(255) DEFAULT NULL,
  "ORDER_ID" bigint NOT NULL,
  PRIMARY KEY (ORDER_PRODUCT_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."order_product_attribute" (
  "ORDER_PRODUCT_ATTRIBUTE_ID" bigint NOT NULL,
  "PRODUCT_ATTRIBUTE_IS_FREE" bit(1) NOT NULL,
  "PRODUCT_ATTRIBUTE_NAME" varchar(255) DEFAULT NULL,
  "PRODUCT_ATTRIBUTE_PRICE" decimal(15,4) NOT NULL,
  "PRODUCT_ATTRIBUTE_VAL_NAME" varchar(255) DEFAULT NULL,
  "PRODUCT_ATTRIBUTE_WEIGHT" decimal(15,4) DEFAULT NULL,
  "PRODUCT_OPTION_ID" bigint NOT NULL,
  "PRODUCT_OPTION_VALUE_ID" bigint NOT NULL,
  "ORDER_PRODUCT_ID" bigint NOT NULL,
  PRIMARY KEY (ORDER_PRODUCT_ATTRIBUTE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."order_product_download" (
  "ORDER_PRODUCT_DOWNLOAD_ID" bigint NOT NULL,
  "DOWNLOAD_COUNT" integer NOT NULL,
  "DOWNLOAD_MAXDAYS" integer NOT NULL,
  "ORDER_PRODUCT_FILENAME" varchar(255) NOT NULL,
  "ORDER_PRODUCT_ID" bigint NOT NULL,
  PRIMARY KEY (ORDER_PRODUCT_DOWNLOAD_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."order_product_price" (
  "ORDER_PRODUCT_PRICE_ID" bigint NOT NULL,
  "DEFAULT_PRICE" bit(1) NOT NULL,
  "PRODUCT_PRICE" decimal(19,2) NOT NULL,
  "PRODUCT_PRICE_CODE" varchar(64) NOT NULL,
  "PRODUCT_PRICE_NAME" varchar(255) DEFAULT NULL,
  "PRODUCT_PRICE_SPECIAL" decimal(19,2) DEFAULT NULL,
  "PRD_PRICE_SPECIAL_END_DT" timestamp DEFAULT NULL,
  "PRD_PRICE_SPECIAL_ST_DT" timestamp DEFAULT NULL,
  "ORDER_PRODUCT_ID" bigint NOT NULL,
  PRIMARY KEY (ORDER_PRODUCT_PRICE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."order_status_history" (
  "ORDER_STATUS_HISTORY_ID" bigint NOT NULL,
  "COMMENTS" text,
  "CUSTOMER_NOTIFIED" integer DEFAULT NULL,
  "DATE_ADDED" timestamp NOT NULL,
  "status" varchar(255) DEFAULT NULL,
  "ORDER_ID" bigint NOT NULL,
  PRIMARY KEY (ORDER_STATUS_HISTORY_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."order_total" (
  "ORDER_ACCOUNT_ID" bigint NOT NULL,
  "MODULE" varchar(60) DEFAULT NULL,
  "CODE" varchar(255) NOT NULL,
  "ORDER_TOTAL_TYPE" varchar(255) DEFAULT NULL,
  "ORDER_VALUE_TYPE" varchar(255) DEFAULT NULL,
  "SORT_ORDER" integer NOT NULL,
  "TEXT" text,
  "TITLE" varchar(255) DEFAULT NULL,
  "VALUE" decimal(15,4) NOT NULL,
  "ORDER_ID" bigint NOT NULL,
  PRIMARY KEY (ORDER_ACCOUNT_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."orders" (
  "ORDER_ID" bigint NOT NULL,
  "BILLING_STREET_ADDRESS" varchar(256) DEFAULT NULL,
  "BILLING_CITY" varchar(100) DEFAULT NULL,
  "BILLING_COMPANY" varchar(100) DEFAULT NULL,
  "BILLING_FIRST_NAME" varchar(64) NOT NULL,
  "BILLING_LAST_NAME" varchar(64) NOT NULL,
  "LATITUDE" varchar(100) DEFAULT NULL,
  "LONGITUDE" varchar(100) DEFAULT NULL,
  "BILLING_POSTCODE" varchar(20) DEFAULT NULL,
  "BILLING_STATE" varchar(100) DEFAULT NULL,
  "BILLING_TELEPHONE" varchar(32) DEFAULT NULL,
  "CHANNEL" varchar(255) DEFAULT NULL,
  "CONFIRMED_ADDRESS" bit(1) DEFAULT NULL,
  "CARD_TYPE" varchar(255) DEFAULT NULL,
  "CC_CVV" varchar(255) DEFAULT NULL,
  "CC_EXPIRES" varchar(255) DEFAULT NULL,
  "CC_NUMBER" varchar(255) DEFAULT NULL,
  "CC_OWNER" varchar(255) DEFAULT NULL,
  "CURRENCY_VALUE" decimal(19,2) DEFAULT NULL,
  "CUSTOMER_AGREED" bit(1) DEFAULT NULL,
  "CUSTOMER_EMAIL_ADDRESS" varchar(50) NOT NULL,
  "CUSTOMER_ID" bigint DEFAULT NULL,
  "DATE_PURCHASED" date DEFAULT NULL,
  "DELIVERY_STREET_ADDRESS" varchar(256) DEFAULT NULL,
  "DELIVERY_CITY" varchar(100) DEFAULT NULL,
  "DELIVERY_COMPANY" varchar(100) DEFAULT NULL,
  "DELIVERY_FIRST_NAME" varchar(64) DEFAULT NULL,
  "DELIVERY_LAST_NAME" varchar(64) DEFAULT NULL,
  "DELIVERY_POSTCODE" varchar(20) DEFAULT NULL,
  "DELIVERY_STATE" varchar(100) DEFAULT NULL,
  "DELIVERY_TELEPHONE" varchar(32) DEFAULT NULL,
  "IP_ADDRESS" varchar(255) DEFAULT NULL,
  "LAST_MODIFIED" timestamp DEFAULT NULL,
  "LOCALE" varchar(255) DEFAULT NULL,
  "ORDER_DATE_FINISHED" timestamp DEFAULT NULL,
  "ORDER_TYPE" varchar(255) DEFAULT NULL,
  "PAYMENT_MODULE_CODE" varchar(255) DEFAULT NULL,
  "PAYMENT_TYPE" varchar(255) DEFAULT NULL,
  "SHIPPING_MODULE_CODE" varchar(255) DEFAULT NULL,
  "ORDER_STATUS" varchar(255) DEFAULT NULL,
  "ORDER_TOTAL" decimal(19,2) DEFAULT NULL,
  "BILLING_COUNTRY_ID" integer NOT NULL,
  "BILLING_ZONE_ID" bigint DEFAULT NULL,
  "CURRENCY_ID" bigint DEFAULT NULL,
  "DELIVERY_COUNTRY_ID" integer DEFAULT NULL,
  "DELIVERY_ZONE_ID" bigint DEFAULT NULL,
  "MERCHANTID" integer DEFAULT NULL,
  PRIMARY KEY (ORDER_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."permission" (
  "PERMISSION_ID" integer NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "PERMISSION_NAME" varchar(255) NOT NULL,
  PRIMARY KEY (PERMISSION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."permission_group" (
  "PERMISSION_ID" integer NOT NULL,
  "GROUP_ID" integer NOT NULL
);


CREATE TABLE IF NOT EXISTS shopizer."product" (
  "PRODUCT_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "AVAILABLE" bit(1) DEFAULT NULL,
  "COND" integer DEFAULT NULL,
  "DATE_AVAILABLE" timestamp DEFAULT NULL,
  "PREORDER" bit(1) DEFAULT NULL,
  "PRODUCT_HEIGHT" decimal(19,2) DEFAULT NULL,
  "PRODUCT_FREE" bit(1) DEFAULT NULL,
  "PRODUCT_LENGTH" decimal(19,2) DEFAULT NULL,
  "QUANTITY_ORDERED" integer DEFAULT NULL,
  "REVIEW_AVG" decimal(19,2) DEFAULT NULL,
  "REVIEW_COUNT" integer DEFAULT NULL,
  "PRODUCT_SHIP" bit(1) DEFAULT NULL,
  "PRODUCT_VIRTUAL" bit(1) DEFAULT NULL,
  "PRODUCT_WEIGHT" decimal(19,2) DEFAULT NULL,
  "PRODUCT_WIDTH" decimal(19,2) DEFAULT NULL,
  "REF_SKU" varchar(255) DEFAULT NULL,
  "RENTAL_DURATION" integer DEFAULT NULL,
  "RENTAL_PERIOD" integer DEFAULT NULL,
  "RENTAL_STATUS" integer DEFAULT NULL,
  "SKU" varchar(255) NOT NULL,
  "SORT_ORDER" integer DEFAULT NULL,
  "MANUFACTURER_ID" bigint DEFAULT NULL,
  "MERCHANT_ID" integer NOT NULL,
  "CUSTOMER_ID" bigint DEFAULT NULL,
  "TAX_CLASS_ID" bigint DEFAULT NULL,
  "PRODUCT_TYPE_ID" bigint DEFAULT NULL,
  PRIMARY KEY (PRODUCT_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_attribute" (
  "PRODUCT_ATTRIBUTE_ID" bigint NOT NULL,
  "PRODUCT_ATTRIBUTE_DEFAULT" bit(1) DEFAULT NULL,
  "PRODUCT_ATTRIBUTE_DISCOUNTED" bit(1) DEFAULT NULL,
  "PRODUCT_ATTRIBUTE_FOR_DISP" bit(1) DEFAULT NULL,
  "PRODUCT_ATTRIBUTE_REQUIRED" bit(1) DEFAULT NULL,
  "PRODUCT_ATTRIBUTE_FREE" bit(1) DEFAULT NULL,
  "PRODUCT_ATRIBUTE_PRICE" decimal(19,2) DEFAULT NULL,
  "PRODUCT_ATTRIBUTE_WEIGHT" decimal(19,2) DEFAULT NULL,
  "PRODUCT_ATTRIBUTE_SORT_ORD" integer DEFAULT NULL,
  "PRODUCT_ID" bigint NOT NULL,
  "OPTION_ID" bigint NOT NULL,
  "OPTION_VALUE_ID" bigint NOT NULL,
  PRIMARY KEY (PRODUCT_ATTRIBUTE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_availability" (
  "PRODUCT_AVAIL_ID" bigint NOT NULL,
  "DATE_AVAILABLE" date DEFAULT NULL,
  "FREE_SHIPPING" bit(1) DEFAULT NULL,
  "QUANTITY" integer NOT NULL,
  "QUANTITY_ORD_MAX" integer DEFAULT NULL,
  "QUANTITY_ORD_MIN" integer DEFAULT NULL,
  "STATUS" bit(1) DEFAULT NULL,
  "REGION" varchar(255) DEFAULT NULL,
  "REGION_VARIANT" varchar(255) DEFAULT NULL,
  "PRODUCT_ID" bigint NOT NULL,
  PRIMARY KEY (PRODUCT_AVAIL_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_category" (
  "PRODUCT_ID" bigint NOT NULL,
  "CATEGORY_ID" bigint NOT NULL,
  PRIMARY KEY (PRODUCT_ID,CATEGORY_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_description" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "META_DESCRIPTION" varchar(255) DEFAULT NULL,
  "META_KEYWORDS" varchar(255) DEFAULT NULL,
  "META_TITLE" varchar(255) DEFAULT NULL,
  "DOWNLOAD_LNK" varchar(255) DEFAULT NULL,
  "PRODUCT_HIGHLIGHT" varchar(255) DEFAULT NULL,
  "SEF_URL" varchar(255) DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "PRODUCT_ID" bigint NOT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_digital" (
  "PRODUCT_DIGITAL_ID" bigint NOT NULL,
  "FILE_NAME" varchar(255) NOT NULL,
  "PRODUCT_ID" bigint NOT NULL,
  PRIMARY KEY (PRODUCT_DIGITAL_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_image" (
  "PRODUCT_IMAGE_ID" bigint NOT NULL,
  "DEFAULT_IMAGE" bit(1) DEFAULT NULL,
  "IMAGE_CROP" bit(1) DEFAULT NULL,
  "IMAGE_TYPE" integer DEFAULT NULL,
  "PRODUCT_IMAGE" varchar(255) DEFAULT NULL,
  "PRODUCT_IMAGE_URL" varchar(255) DEFAULT NULL,
  "PRODUCT_ID" bigint NOT NULL,
  PRIMARY KEY (PRODUCT_IMAGE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_image_description" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "ALT_TAG" varchar(100) DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "PRODUCT_IMAGE_ID" bigint NOT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_option" (
  "PRODUCT_OPTION_ID" bigint NOT NULL,
  "PRODUCT_OPTION_CODE" varchar(255) NOT NULL,
  "PRODUCT_OPTION_SORT_ORD" integer DEFAULT NULL,
  "PRODUCT_OPTION_TYPE" varchar(10) DEFAULT NULL,
  "PRODUCT_OPTION_READ" bit(1) DEFAULT NULL,
  "MERCHANT_ID" integer NOT NULL,
  PRIMARY KEY (PRODUCT_OPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_option_desc" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "PRODUCT_OPTION_COMMENT" text,
  "LANGUAGE_ID" integer NOT NULL,
  "PRODUCT_OPTION_ID" bigint NOT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_option_value" (
  "PRODUCT_OPTION_VALUE_ID" bigint NOT NULL,
  "PRODUCT_OPTION_VAL_CODE" varchar(255) NOT NULL,
  "PRODUCT_OPT_FOR_DISP" bit(1) DEFAULT NULL,
  "PRODUCT_OPT_VAL_IMAGE" varchar(255) DEFAULT NULL,
  "PRODUCT_OPT_VAL_SORT_ORD" integer DEFAULT NULL,
  "MERCHANT_ID" integer NOT NULL,
  PRIMARY KEY (PRODUCT_OPTION_VALUE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_option_value_description" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "PRODUCT_OPTION_VALUE_ID" bigint DEFAULT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_price" (
  "PRODUCT_PRICE_ID" bigint NOT NULL,
  "PRODUCT_PRICE_CODE" varchar(255) NOT NULL,
  "DEFAULT_PRICE" bit(1) DEFAULT NULL,
  "PRODUCT_PRICE_AMOUNT" decimal(19,2) NOT NULL,
  "PRODUCT_PRICE_SPECIAL_AMOUNT" decimal(19,2) DEFAULT NULL,
  "PRODUCT_PRICE_SPECIAL_END_DATE" date DEFAULT NULL,
  "PRODUCT_PRICE_SPECIAL_ST_DATE" date DEFAULT NULL,
  "PRODUCT_PRICE_TYPE" varchar(20) DEFAULT NULL,
  "PRODUCT_AVAIL_ID" bigint NOT NULL,
  PRIMARY KEY (PRODUCT_PRICE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_price_description" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "PRODUCT_PRICE_ID" bigint NOT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_relationship" (
  "PRODUCT_RELATIONSHIP_ID" bigint NOT NULL,
  "ACTIVE" bit(1) DEFAULT NULL,
  "CODE" varchar(255) DEFAULT NULL,
  "PRODUCT_ID" bigint DEFAULT NULL,
  "RELATED_PRODUCT_ID" bigint DEFAULT NULL,
  "MERCHANT_ID" integer NOT NULL,
  PRIMARY KEY (PRODUCT_RELATIONSHIP_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_review" (
  "PRODUCT_REVIEW_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "REVIEW_DATE" timestamp DEFAULT NULL,
  "REVIEWS_RATING" double precision DEFAULT NULL,
  "REVIEWS_READ" bigint DEFAULT NULL,
  "STATUS" integer DEFAULT NULL,
  "CUSTOMERS_ID" bigint DEFAULT NULL,
  "PRODUCT_ID" bigint DEFAULT NULL,
  PRIMARY KEY (PRODUCT_REVIEW_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_review_description" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "PRODUCT_REVIEW_ID" bigint DEFAULT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."product_type" (
  "PRODUCT_TYPE_ID" bigint NOT NULL,
  "PRD_TYPE_ADD_TO_CART" bit(1) DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "PRD_TYPE_CODE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (PRODUCT_TYPE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."shiping_origin" (
  "SHIP_ORIGIN_ID" bigint NOT NULL,
  "ACTIVE" bit(1) DEFAULT NULL,
  "STREET_ADDRESS" varchar(256) NOT NULL,
  "CITY" varchar(100) NOT NULL,
  "POSTCODE" varchar(20) NOT NULL,
  "STATE" varchar(100) DEFAULT NULL,
  "COUNTRY_ID" integer DEFAULT NULL,
  "MERCHANT_ID" integer NOT NULL,
  "ZONE_ID" bigint DEFAULT NULL,
  PRIMARY KEY (SHIP_ORIGIN_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."shipping_quote" (
  "SHIPPING_QUOTE_ID" bigint NOT NULL,
  "CART_ID" bigint DEFAULT NULL,
  "CUSTOMER_ID" bigint DEFAULT NULL,
  "DELIVERY_STREET_ADDRESS" varchar(256) DEFAULT NULL,
  "DELIVERY_CITY" varchar(100) DEFAULT NULL,
  "DELIVERY_COMPANY" varchar(100) DEFAULT NULL,
  "DELIVERY_FIRST_NAME" varchar(64) DEFAULT NULL,
  "DELIVERY_LAST_NAME" varchar(64) DEFAULT NULL,
  "DELIVERY_POSTCODE" varchar(20) DEFAULT NULL,
  "DELIVERY_STATE" varchar(100) DEFAULT NULL,
  "DELIVERY_TELEPHONE" varchar(32) DEFAULT NULL,
  "SHIPPING_NUMBER_DAYS" integer DEFAULT NULL,
  "FREE_SHIPPING" bit(1) DEFAULT NULL,
  "QUOTE_HANDLING" decimal(19,2) DEFAULT NULL,
  "MODULE" varchar(255) NOT NULL,
  "OPTION_CODE" varchar(255) DEFAULT NULL,
  "OPTION_DELIVERY_DATE" timestamp DEFAULT NULL,
  "OPTION_NAME" varchar(255) DEFAULT NULL,
  "OPTION_SHIPPING_DATE" timestamp DEFAULT NULL,
  "ORDER_ID" bigint DEFAULT NULL,
  "QUOTE_PRICE" decimal(19,2) DEFAULT NULL,
  "QUOTE_DATE" timestamp DEFAULT NULL,
  "DELIVERY_COUNTRY_ID" integer DEFAULT NULL,
  "DELIVERY_ZONE_ID" bigint DEFAULT NULL,
  PRIMARY KEY (SHIPPING_QUOTE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."shopping_cart" (
  "SHP_CART_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "CUSTOMER_ID" bigint DEFAULT NULL,
  "SHP_CART_CODE" varchar(255) NOT NULL,
  "MERCHANT_ID" integer NOT NULL,
  PRIMARY KEY (SHP_CART_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."shopping_cart_attr_item" (
  "SHP_CART_ATTR_ITEM_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "PRODUCT_ATTR_ID" bigint NOT NULL,
  "SHP_CART_ITEM_ID" bigint NOT NULL,
  PRIMARY KEY (SHP_CART_ATTR_ITEM_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."shopping_cart_item" (
  "SHP_CART_ITEM_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "PRODUCT_ID" bigint NOT NULL,
  "QUANTITY" integer DEFAULT NULL,
  "SHP_CART_ID" bigint NOT NULL,
  PRIMARY KEY (SHP_CART_ITEM_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."sm_group" (
  "GROUP_ID" integer NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "GROUP_NAME" varchar(255) NOT NULL,
  "GROUP_TYPE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (GROUP_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."sm_sequencer" (
  "SEQ_NAME" varchar(255) NOT NULL,
  "SEQ_COUNT" bigint DEFAULT NULL,
  PRIMARY KEY (SEQ_NAME)
);


CREATE TABLE IF NOT EXISTS shopizer."sm_transaction" (
  "TRANSACTION_ID" bigint NOT NULL,
  "AMOUNT" decimal(19,2) DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DETAILS" text,
  "PAYMENT_TYPE" varchar(255) DEFAULT NULL,
  "TRANSACTION_DATE" timestamp DEFAULT NULL,
  "TRANSACTION_TYPE" varchar(255) DEFAULT NULL,
  "ORDER_ID" bigint DEFAULT NULL,
  PRIMARY KEY (TRANSACTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."system_configuration" (
  "SYSTEM_CONFIG_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "CONFIG_KEY" varchar(255) DEFAULT NULL,
  "VALUE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (SYSTEM_CONFIG_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."system_notification" (
  "SYSTEM_NOTIF_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "END_DATE" date DEFAULT NULL,
  "CONFIG_KEY" varchar(255) DEFAULT NULL,
  "START_DATE" date DEFAULT NULL,
  "VALUE" varchar(255) DEFAULT NULL,
  "MERCHANT_ID" integer DEFAULT NULL,
  "USER_ID" bigint DEFAULT NULL,
  PRIMARY KEY (SYSTEM_NOTIF_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."tax_class" (
  "TAX_CLASS_ID" bigint NOT NULL,
  "TAX_CLASS_CODE" varchar(10) NOT NULL,
  "TAX_CLASS_TITLE" varchar(32) NOT NULL,
  "MERCHANT_ID" integer DEFAULT NULL,
  PRIMARY KEY (TAX_CLASS_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."tax_rate" (
  "TAX_RATE_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "TAX_CODE" varchar(255) NOT NULL,
  "PIGGYBACK" bit(1) DEFAULT NULL,
  "STORE_STATE_PROV" varchar(100) DEFAULT NULL,
  "TAX_PRIORITY" integer DEFAULT NULL,
  "TAX_RATE" decimal(7,4) NOT NULL,
  "COUNTRY_ID" integer NOT NULL,
  "MERCHANT_ID" integer NOT NULL,
  "PARENT_ID" bigint DEFAULT NULL,
  "TAX_CLASS_ID" bigint NOT NULL,
  "ZONE_ID" bigint DEFAULT NULL,
  PRIMARY KEY (TAX_RATE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."tax_rate_description" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "TAX_RATE_ID" bigint DEFAULT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."user" (
  "USER_ID" bigint NOT NULL,
  "ACTIVE" bit(1) DEFAULT NULL,
  "ADMIN_EMAIL" varchar(255) NOT NULL,
  "ADMIN_NAME" varchar(100) NOT NULL,
  "ADMIN_PASSWORD" varchar(60) NOT NULL,
  "ADMIN_A1" varchar(255) DEFAULT NULL,
  "ADMIN_A2" varchar(255) DEFAULT NULL,
  "ADMIN_A3" varchar(255) DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "ADMIN_FIRST_NAME" varchar(255) DEFAULT NULL,
  "LAST_ACCESS" timestamp DEFAULT NULL,
  "ADMIN_LAST_NAME" varchar(255) DEFAULT NULL,
  "LOGIN_ACCESS" timestamp DEFAULT NULL,
  "ADMIN_Q1" varchar(255) DEFAULT NULL,
  "ADMIN_Q2" varchar(255) DEFAULT NULL,
  "ADMIN_Q3" varchar(255) DEFAULT NULL,
  "LANGUAGE_ID" integer DEFAULT NULL,
  "MERCHANT_ID" integer NOT NULL,
  PRIMARY KEY (USER_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."user_group" (
  "USER_ID" bigint NOT NULL,
  "GROUP_ID" integer NOT NULL
);


CREATE TABLE IF NOT EXISTS shopizer."userconnection" (
  "providerId" varchar(255) NOT NULL,
  "providerUserId" varchar(255) NOT NULL,
  "userId" varchar(255) NOT NULL,
  "accessToken" varchar(255) DEFAULT NULL,
  "displayName" varchar(255) DEFAULT NULL,
  "expireTime" bigint DEFAULT NULL,
  "imageUrl" varchar(255) DEFAULT NULL,
  "profileUrl" varchar(255) DEFAULT NULL,
  "refreshToken" varchar(255) DEFAULT NULL,
  "secret" varchar(255) DEFAULT NULL,
  "userRank" integer NOT NULL,
  PRIMARY KEY (providerId,providerUserId,userId)
);


CREATE TABLE IF NOT EXISTS shopizer."zone" (
  "ZONE_ID" bigint NOT NULL,
  "ZONE_CODE" varchar(255) NOT NULL,
  "COUNTRY_ID" integer NOT NULL,
  PRIMARY KEY (ZONE_ID)
);


CREATE TABLE IF NOT EXISTS shopizer."zone_description" (
  "DESCRIPTION_ID" bigint NOT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_MODIFIED" timestamp DEFAULT NULL,
  "UPDT_ID" varchar(20) DEFAULT NULL,
  "DESCRIPTION" text,
  "NAME" varchar(120) NOT NULL,
  "TITLE" varchar(100) DEFAULT NULL,
  "LANGUAGE_ID" integer NOT NULL,
  "ZONE_ID" bigint NOT NULL,
  PRIMARY KEY (DESCRIPTION_ID)
);

