


CREATE TABLE IF NOT EXISTS broadleaf."blc_additional_offer_info" (
  "BLC_ORDER_ORDER_ID" bigint NOT NULL,
  "OFFER_INFO_ID" bigint NOT NULL,
  "OFFER_ID" bigint NOT NULL,
  PRIMARY KEY (BLC_ORDER_ORDER_ID,OFFER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_address" (
  "ADDRESS_ID" bigint NOT NULL,
  "ADDRESS_LINE1" varchar(255) NOT NULL,
  "ADDRESS_LINE2" varchar(255) DEFAULT NULL,
  "ADDRESS_LINE3" varchar(255) DEFAULT NULL,
  "CITY" varchar(255) NOT NULL,
  "COMPANY_NAME" varchar(255) DEFAULT NULL,
  "COUNTY" varchar(255) DEFAULT NULL,
  "EMAIL_ADDRESS" varchar(255) DEFAULT NULL,
  "FAX" varchar(255) DEFAULT NULL,
  "FIRST_NAME" varchar(255) DEFAULT NULL,
  "FULL_NAME" varchar(255) DEFAULT NULL,
  "IS_ACTIVE" bit(1) DEFAULT NULL,
  "IS_BUSINESS" bit(1) DEFAULT NULL,
  "IS_DEFAULT" bit(1) DEFAULT NULL,
  "IS_MAILING" bit(1) DEFAULT NULL,
  "IS_STREET" bit(1) DEFAULT NULL,
  "ISO_COUNTRY_SUB" varchar(255) DEFAULT NULL,
  "LAST_NAME" varchar(255) DEFAULT NULL,
  "POSTAL_CODE" varchar(255) DEFAULT NULL,
  "PRIMARY_PHONE" varchar(255) DEFAULT NULL,
  "SECONDARY_PHONE" varchar(255) DEFAULT NULL,
  "STANDARDIZED" bit(1) DEFAULT NULL,
  "SUB_STATE_PROV_REG" varchar(255) DEFAULT NULL,
  "TOKENIZED_ADDRESS" varchar(255) DEFAULT NULL,
  "VERIFICATION_LEVEL" varchar(255) DEFAULT NULL,
  "ZIP_FOUR" varchar(255) DEFAULT NULL,
  "COUNTRY" varchar(255) DEFAULT NULL,
  "ISO_COUNTRY_ALPHA2" varchar(255) DEFAULT NULL,
  "PHONE_FAX_ID" bigint DEFAULT NULL,
  "PHONE_PRIMARY_ID" bigint DEFAULT NULL,
  "PHONE_SECONDARY_ID" bigint DEFAULT NULL,
  "STATE_PROV_REGION" varchar(255) DEFAULT NULL,
  PRIMARY KEY (ADDRESS_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_admin_module" (
  "ADMIN_MODULE_ID" bigint NOT NULL,
  "DISPLAY_ORDER" integer DEFAULT NULL,
  "ICON" varchar(255) DEFAULT NULL,
  "MODULE_KEY" varchar(255) NOT NULL,
  "NAME" varchar(255) NOT NULL,
  PRIMARY KEY (ADMIN_MODULE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_admin_password_token" (
  "PASSWORD_TOKEN" varchar(255) NOT NULL,
  "ADMIN_USER_ID" bigint NOT NULL,
  "CREATE_DATE" timestamp NOT NULL,
  "TOKEN_USED_DATE" timestamp DEFAULT NULL,
  "TOKEN_USED_FLAG" bit(1) NOT NULL,
  PRIMARY KEY (PASSWORD_TOKEN)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_admin_permission" (
  "ADMIN_PERMISSION_ID" bigint NOT NULL,
  "DESCRIPTION" varchar(255) NOT NULL,
  "IS_FRIENDLY" bit(1) DEFAULT NULL,
  "NAME" varchar(255) NOT NULL,
  "PERMISSION_TYPE" varchar(255) NOT NULL,
  PRIMARY KEY (ADMIN_PERMISSION_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_admin_permission_entity" (
  "ADMIN_PERMISSION_ENTITY_ID" bigint NOT NULL,
  "CEILING_ENTITY" varchar(255) NOT NULL,
  "ADMIN_PERMISSION_ID" bigint DEFAULT NULL,
  PRIMARY KEY (ADMIN_PERMISSION_ENTITY_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_admin_permission_xref" (
  "CHILD_PERMISSION_ID" bigint NOT NULL,
  "ADMIN_PERMISSION_ID" bigint NOT NULL
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_admin_role" (
  "ADMIN_ROLE_ID" bigint NOT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "DESCRIPTION" varchar(255) NOT NULL,
  "NAME" varchar(255) NOT NULL,
  PRIMARY KEY (ADMIN_ROLE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_admin_role_permission_xref" (
  "ADMIN_ROLE_ID" bigint NOT NULL,
  "ADMIN_PERMISSION_ID" bigint NOT NULL,
  PRIMARY KEY (ADMIN_PERMISSION_ID,ADMIN_ROLE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_admin_sec_perm_xref" (
  "ADMIN_SECTION_ID" bigint NOT NULL,
  "ADMIN_PERMISSION_ID" bigint NOT NULL
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_admin_section" (
  "ADMIN_SECTION_ID" bigint NOT NULL,
  "CEILING_ENTITY" varchar(255) DEFAULT NULL,
  "DISPLAY_CONTROLLER" varchar(255) DEFAULT NULL,
  "DISPLAY_ORDER" integer DEFAULT NULL,
  "NAME" varchar(255) NOT NULL,
  "SECTION_KEY" varchar(255) NOT NULL,
  "URL" varchar(255) DEFAULT NULL,
  "USE_DEFAULT_HANDLER" bit(1) DEFAULT NULL,
  "ADMIN_MODULE_ID" bigint NOT NULL,
  PRIMARY KEY (ADMIN_SECTION_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_admin_user" (
  "ADMIN_USER_ID" bigint NOT NULL,
  "ACTIVE_STATUS_FLAG" bit(1) DEFAULT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "EMAIL" varchar(255) NOT NULL,
  "LOGIN" varchar(255) NOT NULL,
  "NAME" varchar(255) NOT NULL,
  "PASSWORD" varchar(255) DEFAULT NULL,
  "PHONE_NUMBER" varchar(255) DEFAULT NULL,
  PRIMARY KEY (ADMIN_USER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_admin_user_addtl_fields" (
  "ATTRIBUTE_ID" bigint NOT NULL,
  "FIELD_NAME" varchar(255) NOT NULL,
  "FIELD_VALUE" varchar(255) DEFAULT NULL,
  "ADMIN_USER_ID" bigint NOT NULL,
  PRIMARY KEY (ATTRIBUTE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_admin_user_permission_xref" (
  "ADMIN_USER_ID" bigint NOT NULL,
  "ADMIN_PERMISSION_ID" bigint NOT NULL,
  PRIMARY KEY (ADMIN_PERMISSION_ID,ADMIN_USER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_admin_user_role_xref" (
  "ADMIN_USER_ID" bigint NOT NULL,
  "ADMIN_ROLE_ID" bigint NOT NULL,
  PRIMARY KEY (ADMIN_ROLE_ID,ADMIN_USER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_admin_user_sandbox" (
  "SANDBOX_ID" bigint DEFAULT NULL,
  "ADMIN_USER_ID" bigint NOT NULL,
  PRIMARY KEY (ADMIN_USER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_asset_desc_map" (
  "STATIC_ASSET_ID" bigint NOT NULL,
  "STATIC_ASSET_DESC_ID" bigint NOT NULL,
  "MAP_KEY" varchar(255) NOT NULL,
  PRIMARY KEY (STATIC_ASSET_ID,MAP_KEY)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_bank_account_payment" (
  "PAYMENT_ID" bigint NOT NULL,
  "ACCOUNT_NUMBER" varchar(255) NOT NULL,
  "REFERENCE_NUMBER" varchar(255) NOT NULL,
  "ROUTING_NUMBER" varchar(255) NOT NULL,
  PRIMARY KEY (PAYMENT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_bund_item_fee_price" (
  "BUND_ITEM_FEE_PRICE_ID" bigint NOT NULL,
  "AMOUNT" decimal(19,5) DEFAULT NULL,
  "IS_TAXABLE" bit(1) DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  "REPORTING_CODE" varchar(255) DEFAULT NULL,
  "BUND_ORDER_ITEM_ID" bigint NOT NULL,
  PRIMARY KEY (BUND_ITEM_FEE_PRICE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_bundle_order_item" (
  "BASE_RETAIL_PRICE" decimal(19,5) DEFAULT NULL,
  "BASE_SALE_PRICE" decimal(19,5) DEFAULT NULL,
  "ORDER_ITEM_ID" bigint NOT NULL,
  "PRODUCT_BUNDLE_ID" bigint DEFAULT NULL,
  "SKU_ID" bigint DEFAULT NULL,
  PRIMARY KEY (ORDER_ITEM_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_candidate_fg_offer" (
  "CANDIDATE_FG_OFFER_ID" bigint NOT NULL,
  "DISCOUNTED_PRICE" decimal(19,5) DEFAULT NULL,
  "FULFILLMENT_GROUP_ID" bigint DEFAULT NULL,
  "OFFER_ID" bigint NOT NULL,
  PRIMARY KEY (CANDIDATE_FG_OFFER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_candidate_item_offer" (
  "CANDIDATE_ITEM_OFFER_ID" bigint NOT NULL,
  "DISCOUNTED_PRICE" decimal(19,5) DEFAULT NULL,
  "OFFER_ID" bigint NOT NULL,
  "ORDER_ITEM_ID" bigint DEFAULT NULL,
  PRIMARY KEY (CANDIDATE_ITEM_OFFER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_candidate_order_offer" (
  "CANDIDATE_ORDER_OFFER_ID" bigint NOT NULL,
  "DISCOUNTED_PRICE" decimal(19,5) DEFAULT NULL,
  "OFFER_ID" bigint NOT NULL,
  "ORDER_ID" bigint DEFAULT NULL,
  PRIMARY KEY (CANDIDATE_ORDER_OFFER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_cat_search_facet_excl_xref" (
  "CAT_EXCL_SEARCH_FACET_ID" bigint NOT NULL,
  "SEQUENCE" decimal(19,2) DEFAULT NULL,
  "CATEGORY_ID" bigint DEFAULT NULL,
  "SEARCH_FACET_ID" bigint DEFAULT NULL,
  PRIMARY KEY (CAT_EXCL_SEARCH_FACET_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_cat_search_facet_xref" (
  "CATEGORY_SEARCH_FACET_ID" bigint NOT NULL,
  "SEQUENCE" decimal(19,2) DEFAULT NULL,
  "CATEGORY_ID" bigint DEFAULT NULL,
  "SEARCH_FACET_ID" bigint DEFAULT NULL,
  PRIMARY KEY (CATEGORY_SEARCH_FACET_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_cat_site_map_gen_cfg" (
  "ENDING_DEPTH" integer NOT NULL,
  "STARTING_DEPTH" integer NOT NULL,
  "GEN_CONFIG_ID" bigint NOT NULL,
  "ROOT_CATEGORY_ID" bigint NOT NULL,
  PRIMARY KEY (GEN_CONFIG_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_catalog" (
  "CATALOG_ID" bigint NOT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  PRIMARY KEY (CATALOG_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_category" (
  "CATEGORY_ID" bigint NOT NULL,
  "ACTIVE_END_DATE" timestamp DEFAULT NULL,
  "ACTIVE_START_DATE" timestamp DEFAULT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "DESCRIPTION" varchar(255) DEFAULT NULL,
  "DISPLAY_TEMPLATE" varchar(255) DEFAULT NULL,
  "EXTERNAL_ID" varchar(255) DEFAULT NULL,
  "FULFILLMENT_TYPE" varchar(255) DEFAULT NULL,
  "INVENTORY_TYPE" varchar(255) DEFAULT NULL,
  "LONG_DESCRIPTION" text,
  "META_DESC" varchar(255) DEFAULT NULL,
  "META_TITLE" varchar(255) DEFAULT NULL,
  "NAME" varchar(255) NOT NULL,
  "OVERRIDE_GENERATED_URL" bit(1) DEFAULT NULL,
  "PRODUCT_DESC_PATTERN_OVERRIDE" varchar(255) DEFAULT NULL,
  "PRODUCT_TITLE_PATTERN_OVERRIDE" varchar(255) DEFAULT NULL,
  "ROOT_DISPLAY_ORDER" decimal(10,6) DEFAULT NULL,
  "TAX_CODE" varchar(255) DEFAULT NULL,
  "URL" varchar(255) DEFAULT NULL,
  "URL_KEY" varchar(255) DEFAULT NULL,
  "DEFAULT_PARENT_CATEGORY_ID" bigint DEFAULT NULL,
  PRIMARY KEY (CATEGORY_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_category_attribute" (
  "CATEGORY_ATTRIBUTE_ID" bigint NOT NULL,
  "NAME" varchar(255) NOT NULL,
  "VALUE" varchar(255) DEFAULT NULL,
  "CATEGORY_ID" bigint NOT NULL,
  PRIMARY KEY (CATEGORY_ATTRIBUTE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_category_media_map" (
  "CATEGORY_MEDIA_ID" bigint NOT NULL,
  "MAP_KEY" varchar(255) NOT NULL,
  "BLC_CATEGORY_CATEGORY_ID" bigint NOT NULL,
  "MEDIA_ID" bigint DEFAULT NULL,
  PRIMARY KEY (CATEGORY_MEDIA_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_category_product_xref" (
  "CATEGORY_PRODUCT_ID" bigint NOT NULL,
  "DEFAULT_REFERENCE" bit(1) DEFAULT NULL,
  "DISPLAY_ORDER" decimal(10,6) DEFAULT NULL,
  "CATEGORY_ID" bigint NOT NULL,
  "PRODUCT_ID" bigint NOT NULL,
  PRIMARY KEY (CATEGORY_PRODUCT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_category_xref" (
  "CATEGORY_XREF_ID" bigint NOT NULL,
  "DEFAULT_REFERENCE" bit(1) DEFAULT NULL,
  "DISPLAY_ORDER" decimal(10,6) DEFAULT NULL,
  "CATEGORY_ID" bigint NOT NULL,
  "SUB_CATEGORY_ID" bigint NOT NULL,
  PRIMARY KEY (CATEGORY_XREF_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_challenge_question" (
  "QUESTION_ID" bigint NOT NULL,
  "QUESTION" varchar(255) NOT NULL,
  PRIMARY KEY (QUESTION_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_cms_menu" (
  "MENU_ID" bigint NOT NULL,
  "NAME" varchar(255) NOT NULL,
  PRIMARY KEY (MENU_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_cms_menu_item" (
  "MENU_ITEM_ID" bigint NOT NULL,
  "ACTION_URL" varchar(255) DEFAULT NULL,
  "ALT_TEXT" varchar(255) DEFAULT NULL,
  "CUSTOM_HTML" text,
  "IMAGE_URL" varchar(255) DEFAULT NULL,
  "LABEL" varchar(255) DEFAULT NULL,
  "SEQUENCE" decimal(10,6) DEFAULT NULL,
  "MENU_ITEM_TYPE" varchar(255) DEFAULT NULL,
  "LINKED_MENU_ID" bigint DEFAULT NULL,
  "LINKED_PAGE_ID" bigint DEFAULT NULL,
  "PARENT_MENU_ID" bigint DEFAULT NULL,
  PRIMARY KEY (MENU_ITEM_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_code_types" (
  "CODE_ID" bigint NOT NULL,
  "CODE_TYPE" varchar(255) NOT NULL,
  "CODE_DESC" varchar(255) DEFAULT NULL,
  "CODE_KEY" varchar(255) NOT NULL,
  "MODIFIABLE" char(1) DEFAULT NULL,
  PRIMARY KEY (CODE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_country" (
  "ABBREVIATION" varchar(255) NOT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "NAME" varchar(255) NOT NULL,
  PRIMARY KEY (ABBREVIATION)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_country_sub" (
  "ABBREVIATION" varchar(255) NOT NULL,
  "ALT_ABBREVIATION" varchar(255) DEFAULT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "NAME" varchar(255) NOT NULL,
  "COUNTRY_SUB_CAT" bigint DEFAULT NULL,
  "COUNTRY" varchar(255) NOT NULL,
  PRIMARY KEY (ABBREVIATION)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_country_sub_cat" (
  "COUNTRY_SUB_CAT_ID" bigint NOT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "NAME" varchar(255) NOT NULL,
  PRIMARY KEY (COUNTRY_SUB_CAT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_credit_card_payment" (
  "PAYMENT_ID" bigint NOT NULL,
  "EXPIRATION_MONTH" integer NOT NULL,
  "EXPIRATION_YEAR" integer NOT NULL,
  "NAME_ON_CARD" varchar(255) NOT NULL,
  "PAN" varchar(255) NOT NULL,
  "REFERENCE_NUMBER" varchar(255) NOT NULL,
  PRIMARY KEY (PAYMENT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_currency" (
  "CURRENCY_CODE" varchar(255) NOT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "DEFAULT_FLAG" bit(1) DEFAULT NULL,
  "FRIENDLY_NAME" varchar(255) DEFAULT NULL,
  PRIMARY KEY (CURRENCY_CODE)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_cust_site_map_gen_cfg" (
  "GEN_CONFIG_ID" bigint NOT NULL,
  PRIMARY KEY (GEN_CONFIG_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_customer" (
  "CUSTOMER_ID" bigint NOT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "CHALLENGE_ANSWER" varchar(255) DEFAULT NULL,
  "DEACTIVATED" bit(1) DEFAULT NULL,
  "EMAIL_ADDRESS" varchar(255) DEFAULT NULL,
  "EXTERNAL_ID" varchar(255) DEFAULT NULL,
  "FIRST_NAME" varchar(255) DEFAULT NULL,
  "IS_TAX_EXEMPT" bit(1) DEFAULT NULL,
  "LAST_NAME" varchar(255) DEFAULT NULL,
  "PASSWORD" varchar(255) DEFAULT NULL,
  "PASSWORD_CHANGE_REQUIRED" bit(1) DEFAULT NULL,
  "IS_PREVIEW" bit(1) DEFAULT NULL,
  "RECEIVE_EMAIL" bit(1) DEFAULT NULL,
  "IS_REGISTERED" bit(1) DEFAULT NULL,
  "TAX_EXEMPTION_CODE" varchar(255) DEFAULT NULL,
  "USER_NAME" varchar(255) DEFAULT NULL,
  "CHALLENGE_QUESTION_ID" bigint DEFAULT NULL,
  "LOCALE_CODE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (CUSTOMER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_customer_address" (
  "CUSTOMER_ADDRESS_ID" bigint NOT NULL,
  "ADDRESS_NAME" varchar(255) DEFAULT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "ADDRESS_ID" bigint NOT NULL,
  "CUSTOMER_ID" bigint NOT NULL,
  PRIMARY KEY (CUSTOMER_ADDRESS_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_customer_attribute" (
  "CUSTOMER_ATTR_ID" bigint NOT NULL,
  "NAME" varchar(255) NOT NULL,
  "VALUE" varchar(255) DEFAULT NULL,
  "CUSTOMER_ID" bigint NOT NULL,
  PRIMARY KEY (CUSTOMER_ATTR_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_customer_offer_xref" (
  "CUSTOMER_OFFER_ID" bigint NOT NULL,
  "CUSTOMER_ID" bigint NOT NULL,
  "OFFER_ID" bigint NOT NULL,
  PRIMARY KEY (CUSTOMER_OFFER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_customer_password_token" (
  "PASSWORD_TOKEN" varchar(255) NOT NULL,
  "CREATE_DATE" timestamp NOT NULL,
  "CUSTOMER_ID" bigint NOT NULL,
  "TOKEN_USED_DATE" timestamp DEFAULT NULL,
  "TOKEN_USED_FLAG" bit(1) NOT NULL,
  PRIMARY KEY (PASSWORD_TOKEN)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_customer_payment" (
  "CUSTOMER_PAYMENT_ID" bigint NOT NULL,
  "IS_DEFAULT" bit(1) DEFAULT NULL,
  "GATEWAY_TYPE" varchar(255) DEFAULT NULL,
  "PAYMENT_TOKEN" varchar(255) DEFAULT NULL,
  "PAYMENT_TYPE" varchar(255) DEFAULT NULL,
  "ADDRESS_ID" bigint DEFAULT NULL,
  "CUSTOMER_ID" bigint NOT NULL,
  PRIMARY KEY (CUSTOMER_PAYMENT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_customer_payment_fields" (
  "CUSTOMER_PAYMENT_ID" bigint NOT NULL,
  "FIELD_VALUE" text,
  "FIELD_NAME" varchar(255) NOT NULL,
  PRIMARY KEY (CUSTOMER_PAYMENT_ID,FIELD_NAME)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_customer_phone" (
  "CUSTOMER_PHONE_ID" bigint NOT NULL,
  "PHONE_NAME" varchar(255) DEFAULT NULL,
  "CUSTOMER_ID" bigint NOT NULL,
  "PHONE_ID" bigint NOT NULL,
  PRIMARY KEY (CUSTOMER_PHONE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_customer_role" (
  "CUSTOMER_ROLE_ID" bigint NOT NULL,
  "CUSTOMER_ID" bigint NOT NULL,
  "ROLE_ID" bigint NOT NULL,
  PRIMARY KEY (CUSTOMER_ROLE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_data_drvn_enum" (
  "ENUM_ID" bigint NOT NULL,
  "ENUM_KEY" varchar(255) DEFAULT NULL,
  "MODIFIABLE" bit(1) DEFAULT NULL,
  PRIMARY KEY (ENUM_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_data_drvn_enum_val" (
  "ENUM_VAL_ID" bigint NOT NULL,
  "DISPLAY" varchar(255) DEFAULT NULL,
  "HIDDEN" bit(1) DEFAULT NULL,
  "ENUM_KEY" varchar(255) DEFAULT NULL,
  "ENUM_TYPE" bigint DEFAULT NULL,
  PRIMARY KEY (ENUM_VAL_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_disc_item_fee_price" (
  "DISC_ITEM_FEE_PRICE_ID" bigint NOT NULL,
  "AMOUNT" decimal(19,5) DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  "REPORTING_CODE" varchar(255) DEFAULT NULL,
  "ORDER_ITEM_ID" bigint NOT NULL,
  PRIMARY KEY (DISC_ITEM_FEE_PRICE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_discrete_order_item" (
  "BASE_RETAIL_PRICE" decimal(19,5) DEFAULT NULL,
  "BASE_SALE_PRICE" decimal(19,5) DEFAULT NULL,
  "ORDER_ITEM_ID" bigint NOT NULL,
  "BUNDLE_ORDER_ITEM_ID" bigint DEFAULT NULL,
  "PRODUCT_ID" bigint DEFAULT NULL,
  "SKU_ID" bigint NOT NULL,
  "SKU_BUNDLE_ITEM_ID" bigint DEFAULT NULL,
  PRIMARY KEY (ORDER_ITEM_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_dyn_discrete_order_item" (
  "ORDER_ITEM_ID" bigint NOT NULL,
  PRIMARY KEY (ORDER_ITEM_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_email_tracking" (
  "EMAIL_TRACKING_ID" bigint NOT NULL,
  "DATE_SENT" timestamp DEFAULT NULL,
  "EMAIL_ADDRESS" varchar(255) DEFAULT NULL,
  "TYPE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (EMAIL_TRACKING_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_email_tracking_clicks" (
  "CLICK_ID" bigint NOT NULL,
  "CUSTOMER_ID" varchar(255) DEFAULT NULL,
  "DATE_CLICKED" timestamp NOT NULL,
  "DESTINATION_URI" varchar(255) DEFAULT NULL,
  "QUERY_STRING" varchar(255) DEFAULT NULL,
  "EMAIL_TRACKING_ID" bigint NOT NULL,
  PRIMARY KEY (CLICK_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_email_tracking_opens" (
  "OPEN_ID" bigint NOT NULL,
  "DATE_OPENED" timestamp DEFAULT NULL,
  "USER_AGENT" varchar(255) DEFAULT NULL,
  "EMAIL_TRACKING_ID" bigint DEFAULT NULL,
  PRIMARY KEY (OPEN_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fg_adjustment" (
  "FG_ADJUSTMENT_ID" bigint NOT NULL,
  "ADJUSTMENT_REASON" varchar(255) NOT NULL,
  "ADJUSTMENT_VALUE" decimal(19,5) NOT NULL,
  "FULFILLMENT_GROUP_ID" bigint DEFAULT NULL,
  "OFFER_ID" bigint NOT NULL,
  PRIMARY KEY (FG_ADJUSTMENT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fg_fee_tax_xref" (
  "FULFILLMENT_GROUP_FEE_ID" bigint NOT NULL,
  "TAX_DETAIL_ID" bigint NOT NULL
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fg_fg_tax_xref" (
  "FULFILLMENT_GROUP_ID" bigint NOT NULL,
  "TAX_DETAIL_ID" bigint NOT NULL
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fg_item_tax_xref" (
  "FULFILLMENT_GROUP_ITEM_ID" bigint NOT NULL,
  "TAX_DETAIL_ID" bigint NOT NULL
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_field" (
  "FIELD_ID" bigint NOT NULL,
  "ABBREVIATION" varchar(255) DEFAULT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "ENTITY_TYPE" varchar(255) NOT NULL,
  "FRIENDLY_NAME" varchar(255) DEFAULT NULL,
  "OVERRIDE_GENERATED_PROP_NAME" bit(1) DEFAULT NULL,
  "PROPERTY_NAME" varchar(255) NOT NULL,
  "TRANSLATABLE" bit(1) DEFAULT NULL,
  PRIMARY KEY (FIELD_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fld_def" (
  "FLD_DEF_ID" bigint NOT NULL,
  "ALLOW_MULTIPLES" bit(1) DEFAULT NULL,
  "COLUMN_WIDTH" varchar(255) DEFAULT NULL,
  "FLD_ORDER" integer DEFAULT NULL,
  "FLD_TYPE" varchar(255) DEFAULT NULL,
  "FRIENDLY_NAME" varchar(255) DEFAULT NULL,
  "HELP_TEXT" varchar(255) DEFAULT NULL,
  "HIDDEN_FLAG" bit(1) DEFAULT NULL,
  "HINT" varchar(255) DEFAULT NULL,
  "MAX_LENGTH" integer DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  "REQUIRED_FLAG" bit(1) DEFAULT NULL,
  "SECURITY_LEVEL" varchar(255) DEFAULT NULL,
  "TEXT_AREA_FLAG" bit(1) DEFAULT NULL,
  "TOOLTIP" varchar(255) DEFAULT NULL,
  "VLDTN_ERROR_MSSG_KEY" varchar(255) DEFAULT NULL,
  "VLDTN_REGEX" varchar(255) DEFAULT NULL,
  "ENUM_ID" bigint DEFAULT NULL,
  "FLD_GROUP_ID" bigint DEFAULT NULL,
  PRIMARY KEY (FLD_DEF_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fld_enum" (
  "FLD_ENUM_ID" bigint NOT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  PRIMARY KEY (FLD_ENUM_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fld_enum_item" (
  "FLD_ENUM_ITEM_ID" bigint NOT NULL,
  "FLD_ORDER" integer DEFAULT NULL,
  "FRIENDLY_NAME" varchar(255) DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  "FLD_ENUM_ID" bigint DEFAULT NULL,
  PRIMARY KEY (FLD_ENUM_ITEM_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fld_group" (
  "FLD_GROUP_ID" bigint NOT NULL,
  "INIT_COLLAPSED_FLAG" bit(1) DEFAULT NULL,
  "IS_MASTER_FIELD_GROUP" bit(1) DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  PRIMARY KEY (FLD_GROUP_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fulfillment_group" (
  "FULFILLMENT_GROUP_ID" bigint NOT NULL,
  "DELIVERY_INSTRUCTION" varchar(255) DEFAULT NULL,
  "PRICE" decimal(19,5) DEFAULT NULL,
  "SHIPPING_PRICE_TAXABLE" bit(1) DEFAULT NULL,
  "MERCHANDISE_TOTAL" decimal(19,5) DEFAULT NULL,
  "METHOD" varchar(255) DEFAULT NULL,
  "IS_PRIMARY" bit(1) DEFAULT NULL,
  "REFERENCE_NUMBER" varchar(255) DEFAULT NULL,
  "RETAIL_PRICE" decimal(19,5) DEFAULT NULL,
  "SALE_PRICE" decimal(19,5) DEFAULT NULL,
  "FULFILLMENT_GROUP_SEQUNCE" integer DEFAULT NULL,
  "SERVICE" varchar(255) DEFAULT NULL,
  "SHIPPING_OVERRIDE" bit(1) DEFAULT NULL,
  "STATUS" varchar(255) DEFAULT NULL,
  "TOTAL" decimal(19,5) DEFAULT NULL,
  "TOTAL_FEE_TAX" decimal(19,5) DEFAULT NULL,
  "TOTAL_FG_TAX" decimal(19,5) DEFAULT NULL,
  "TOTAL_ITEM_TAX" decimal(19,5) DEFAULT NULL,
  "TOTAL_TAX" decimal(19,5) DEFAULT NULL,
  "TYPE" varchar(255) DEFAULT NULL,
  "ADDRESS_ID" bigint DEFAULT NULL,
  "FULFILLMENT_OPTION_ID" bigint DEFAULT NULL,
  "ORDER_ID" bigint NOT NULL,
  "PERSONAL_MESSAGE_ID" bigint DEFAULT NULL,
  "PHONE_ID" bigint DEFAULT NULL,
  PRIMARY KEY (FULFILLMENT_GROUP_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fulfillment_group_fee" (
  "FULFILLMENT_GROUP_FEE_ID" bigint NOT NULL,
  "AMOUNT" decimal(19,5) DEFAULT NULL,
  "FEE_TAXABLE_FLAG" bit(1) DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  "REPORTING_CODE" varchar(255) DEFAULT NULL,
  "TOTAL_FEE_TAX" decimal(19,5) DEFAULT NULL,
  "FULFILLMENT_GROUP_ID" bigint NOT NULL,
  PRIMARY KEY (FULFILLMENT_GROUP_FEE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fulfillment_group_item" (
  "FULFILLMENT_GROUP_ITEM_ID" bigint NOT NULL,
  "PRORATED_ORDER_ADJ" decimal(19,2) DEFAULT NULL,
  "QUANTITY" integer NOT NULL,
  "STATUS" varchar(255) DEFAULT NULL,
  "TOTAL_ITEM_AMOUNT" decimal(19,5) DEFAULT NULL,
  "TOTAL_ITEM_TAXABLE_AMOUNT" decimal(19,5) DEFAULT NULL,
  "TOTAL_ITEM_TAX" decimal(19,5) DEFAULT NULL,
  "FULFILLMENT_GROUP_ID" bigint NOT NULL,
  "ORDER_ITEM_ID" bigint NOT NULL,
  PRIMARY KEY (FULFILLMENT_GROUP_ITEM_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fulfillment_opt_banded_prc" (
  "FULFILLMENT_OPTION_ID" bigint NOT NULL,
  PRIMARY KEY (FULFILLMENT_OPTION_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fulfillment_opt_banded_wgt" (
  "FULFILLMENT_OPTION_ID" bigint NOT NULL,
  PRIMARY KEY (FULFILLMENT_OPTION_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fulfillment_option" (
  "FULFILLMENT_OPTION_ID" bigint NOT NULL,
  "FULFILLMENT_TYPE" varchar(255) NOT NULL,
  "LONG_DESCRIPTION" text,
  "NAME" varchar(255) DEFAULT NULL,
  "TAX_CODE" varchar(255) DEFAULT NULL,
  "TAXABLE" bit(1) DEFAULT NULL,
  "USE_FLAT_RATES" bit(1) DEFAULT NULL,
  PRIMARY KEY (FULFILLMENT_OPTION_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fulfillment_option_fixed" (
  "PRICE" decimal(19,5) NOT NULL,
  "FULFILLMENT_OPTION_ID" bigint NOT NULL,
  "CURRENCY_CODE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (FULFILLMENT_OPTION_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fulfillment_price_band" (
  "FULFILLMENT_PRICE_BAND_ID" bigint NOT NULL,
  "RESULT_AMOUNT" decimal(19,5) NOT NULL,
  "RESULT_AMOUNT_TYPE" varchar(255) NOT NULL,
  "RETAIL_PRICE_MINIMUM_AMOUNT" decimal(19,5) NOT NULL,
  "FULFILLMENT_OPTION_ID" bigint DEFAULT NULL,
  PRIMARY KEY (FULFILLMENT_PRICE_BAND_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_fulfillment_weight_band" (
  "FULFILLMENT_WEIGHT_BAND_ID" bigint NOT NULL,
  "RESULT_AMOUNT" decimal(19,5) NOT NULL,
  "RESULT_AMOUNT_TYPE" varchar(255) NOT NULL,
  "MINIMUM_WEIGHT" decimal(19,5) DEFAULT NULL,
  "WEIGHT_UNIT_OF_MEASURE" varchar(255) DEFAULT NULL,
  "FULFILLMENT_OPTION_ID" bigint DEFAULT NULL,
  PRIMARY KEY (FULFILLMENT_WEIGHT_BAND_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_gift_card_payment" (
  "PAYMENT_ID" bigint NOT NULL,
  "PAN" varchar(255) NOT NULL,
  "PIN" varchar(255) DEFAULT NULL,
  "REFERENCE_NUMBER" varchar(255) NOT NULL,
  PRIMARY KEY (PAYMENT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_giftwrap_order_item" (
  "ORDER_ITEM_ID" bigint NOT NULL,
  PRIMARY KEY (ORDER_ITEM_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_id_generation" (
  "ID_TYPE" varchar(255) NOT NULL,
  "BATCH_SIZE" bigint NOT NULL,
  "BATCH_START" bigint NOT NULL,
  "ID_MIN" bigint DEFAULT NULL,
  "ID_MAX" bigint DEFAULT NULL,
  "version" integer DEFAULT NULL,
  PRIMARY KEY (ID_TYPE)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_img_static_asset" (
  "HEIGHT" integer DEFAULT NULL,
  "WIDTH" integer DEFAULT NULL,
  "STATIC_ASSET_ID" bigint NOT NULL,
  PRIMARY KEY (STATIC_ASSET_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_index_field" (
  "ARCHIVED" char(1) DEFAULT NULL,
  "SEARCHABLE" bit(1) DEFAULT NULL,
  "FIELD_ID" bigint NOT NULL,
  PRIMARY KEY (INDEX_FIELD_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_index_field_type" (
  "ARCHIVED" char(1) DEFAULT NULL,
  "FIELD_TYPE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (INDEX_FIELD_TYPE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_iso_country" (
  "ALPHA_2" varchar(255) NOT NULL,
  "ALPHA_3" varchar(255) DEFAULT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  "NUMERIC_CODE" integer DEFAULT NULL,
  "STATUS" varchar(255) DEFAULT NULL,
  PRIMARY KEY (ALPHA_2)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_item_offer_qualifier" (
  "ITEM_OFFER_QUALIFIER_ID" bigint NOT NULL,
  "QUANTITY" bigint DEFAULT NULL,
  "OFFER_ID" bigint NOT NULL,
  "ORDER_ITEM_ID" bigint DEFAULT NULL,
  PRIMARY KEY (ITEM_OFFER_QUALIFIER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_locale" (
  "LOCALE_CODE" varchar(255) NOT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "DEFAULT_FLAG" bit(1) DEFAULT NULL,
  "FRIENDLY_NAME" varchar(255) DEFAULT NULL,
  "USE_IN_SEARCH_INDEX" bit(1) DEFAULT NULL,
  "CURRENCY_CODE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (LOCALE_CODE)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_media" (
  "MEDIA_ID" bigint NOT NULL,
  "ALT_TEXT" varchar(255) DEFAULT NULL,
  "TAGS" varchar(255) DEFAULT NULL,
  "TITLE" varchar(255) DEFAULT NULL,
  "URL" varchar(255) NOT NULL,
  PRIMARY KEY (MEDIA_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_module_configuration" (
  "MODULE_CONFIG_ID" bigint NOT NULL,
  "ACTIVE_END_DATE" timestamp DEFAULT NULL,
  "ACTIVE_START_DATE" timestamp DEFAULT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "CONFIG_TYPE" varchar(255) NOT NULL,
  "IS_DEFAULT" bit(1) NOT NULL,
  "MODULE_NAME" varchar(255) NOT NULL,
  "MODULE_PRIORITY" integer NOT NULL,
  PRIMARY KEY (MODULE_CONFIG_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_offer" (
  "OFFER_ID" bigint NOT NULL,
  "APPLY_TO_CHILD_ITEMS" bit(1) DEFAULT NULL,
  "APPLY_TO_SALE_PRICE" bit(1) DEFAULT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "AUTOMATICALLY_ADDED" bit(1) DEFAULT NULL,
  "COMBINABLE_WITH_OTHER_OFFERS" bit(1) DEFAULT NULL,
  "OFFER_DESCRIPTION" varchar(255) DEFAULT NULL,
  "OFFER_DISCOUNT_TYPE" varchar(255) DEFAULT NULL,
  "END_DATE" timestamp DEFAULT NULL,
  "MARKETING_MESSASGE" varchar(255) DEFAULT NULL,
  "MAX_USES_PER_CUSTOMER" bigint DEFAULT NULL,
  "MAX_USES" integer DEFAULT NULL,
  "OFFER_NAME" varchar(255) NOT NULL,
  "OFFER_ITEM_QUALIFIER_RULE" varchar(255) DEFAULT NULL,
  "OFFER_ITEM_TARGET_RULE" varchar(255) DEFAULT NULL,
  "ORDER_MIN_TOTAL" decimal(19,5) DEFAULT NULL,
  "OFFER_PRIORITY" integer DEFAULT NULL,
  "QUALIFYING_ITEM_MIN_TOTAL" decimal(19,5) DEFAULT NULL,
  "REQUIRES_RELATED_TAR_QUAL" bit(1) DEFAULT NULL,
  "START_DATE" timestamp DEFAULT NULL,
  "TARGET_MIN_TOTAL" decimal(19,5) DEFAULT NULL,
  "TARGET_SYSTEM" varchar(255) DEFAULT NULL,
  "TOTALITARIAN_OFFER" bit(1) DEFAULT NULL,
  "OFFER_TYPE" varchar(255) NOT NULL,
  "OFFER_VALUE" decimal(19,5) NOT NULL,
  PRIMARY KEY (OFFER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_offer_audit" (
  "OFFER_AUDIT_ID" bigint NOT NULL,
  "CUSTOMER_ID" bigint DEFAULT NULL,
  "OFFER_CODE_ID" bigint DEFAULT NULL,
  "OFFER_ID" bigint DEFAULT NULL,
  "ORDER_ID" bigint DEFAULT NULL,
  "REDEEMED_DATE" timestamp DEFAULT NULL,
  PRIMARY KEY (OFFER_AUDIT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_offer_code" (
  "OFFER_CODE_ID" bigint NOT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "EMAIL_ADDRESS" varchar(255) DEFAULT NULL,
  "MAX_USES" integer DEFAULT NULL,
  "OFFER_CODE" varchar(255) NOT NULL,
  "END_DATE" timestamp DEFAULT NULL,
  "START_DATE" timestamp DEFAULT NULL,
  "USES" integer DEFAULT NULL,
  "OFFER_ID" bigint NOT NULL,
  PRIMARY KEY (OFFER_CODE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_offer_info" (
  "OFFER_INFO_ID" bigint NOT NULL,
  PRIMARY KEY (OFFER_INFO_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_offer_info_fields" (
  "OFFER_INFO_FIELDS_ID" bigint NOT NULL,
  "FIELD_VALUE" varchar(255) DEFAULT NULL,
  "FIELD_NAME" varchar(255) NOT NULL,
  PRIMARY KEY (OFFER_INFO_FIELDS_ID,FIELD_NAME)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_offer_item_criteria" (
  "OFFER_ITEM_CRITERIA_ID" bigint NOT NULL,
  "ORDER_ITEM_MATCH_RULE" text,
  "QUANTITY" integer NOT NULL,
  PRIMARY KEY (OFFER_ITEM_CRITERIA_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_offer_rule" (
  "OFFER_RULE_ID" bigint NOT NULL,
  "MATCH_RULE" text,
  PRIMARY KEY (OFFER_RULE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_offer_rule_map" (
  "OFFER_OFFER_RULE_ID" bigint NOT NULL,
  "MAP_KEY" varchar(255) NOT NULL,
  "BLC_OFFER_OFFER_ID" bigint NOT NULL,
  "OFFER_RULE_ID" bigint DEFAULT NULL,
  PRIMARY KEY (OFFER_OFFER_RULE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order" (
  "ORDER_ID" bigint NOT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "EMAIL_ADDRESS" varchar(255) DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  "ORDER_NUMBER" varchar(255) DEFAULT NULL,
  "IS_PREVIEW" bit(1) DEFAULT NULL,
  "ORDER_STATUS" varchar(255) DEFAULT NULL,
  "ORDER_SUBTOTAL" decimal(19,5) DEFAULT NULL,
  "SUBMIT_DATE" timestamp DEFAULT NULL,
  "TAX_OVERRIDE" bit(1) DEFAULT NULL,
  "ORDER_TOTAL" decimal(19,5) DEFAULT NULL,
  "TOTAL_SHIPPING" decimal(19,5) DEFAULT NULL,
  "TOTAL_TAX" decimal(19,5) DEFAULT NULL,
  "CURRENCY_CODE" varchar(255) DEFAULT NULL,
  "CUSTOMER_ID" bigint NOT NULL,
  "LOCALE_CODE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (ORDER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order_adjustment" (
  "ORDER_ADJUSTMENT_ID" bigint NOT NULL,
  "ADJUSTMENT_REASON" varchar(255) NOT NULL,
  "ADJUSTMENT_VALUE" decimal(19,5) NOT NULL,
  "OFFER_ID" bigint NOT NULL,
  "ORDER_ID" bigint DEFAULT NULL,
  PRIMARY KEY (ORDER_ADJUSTMENT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order_attribute" (
  "ORDER_ATTRIBUTE_ID" bigint NOT NULL,
  "NAME" varchar(255) NOT NULL,
  "VALUE" varchar(255) DEFAULT NULL,
  "ORDER_ID" bigint NOT NULL,
  PRIMARY KEY (ORDER_ATTRIBUTE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order_item" (
  "ORDER_ITEM_ID" bigint NOT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "DISCOUNTS_ALLOWED" bit(1) DEFAULT NULL,
  "HAS_VALIDATION_ERRORS" bit(1) DEFAULT NULL,
  "ITEM_TAXABLE_FLAG" bit(1) DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  "ORDER_ITEM_TYPE" varchar(255) DEFAULT NULL,
  "PRICE" decimal(19,5) DEFAULT NULL,
  "QUANTITY" integer NOT NULL,
  "RETAIL_PRICE" decimal(19,5) DEFAULT NULL,
  "RETAIL_PRICE_OVERRIDE" bit(1) DEFAULT NULL,
  "SALE_PRICE" decimal(19,5) DEFAULT NULL,
  "SALE_PRICE_OVERRIDE" bit(1) DEFAULT NULL,
  "TOTAL_TAX" decimal(19,2) DEFAULT NULL,
  "CATEGORY_ID" bigint DEFAULT NULL,
  "GIFT_WRAP_ITEM_ID" bigint DEFAULT NULL,
  "ORDER_ID" bigint DEFAULT NULL,
  "PARENT_ORDER_ITEM_ID" bigint DEFAULT NULL,
  "PERSONAL_MESSAGE_ID" bigint DEFAULT NULL,
  PRIMARY KEY (ORDER_ITEM_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order_item_add_attr" (
  "ORDER_ITEM_ID" bigint NOT NULL,
  "VALUE" varchar(255) DEFAULT NULL,
  "NAME" varchar(255) NOT NULL,
  PRIMARY KEY (ORDER_ITEM_ID,NAME)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order_item_adjustment" (
  "ORDER_ITEM_ADJUSTMENT_ID" bigint NOT NULL,
  "APPLIED_TO_SALE_PRICE" bit(1) DEFAULT NULL,
  "ADJUSTMENT_REASON" varchar(255) NOT NULL,
  "ADJUSTMENT_VALUE" decimal(19,5) NOT NULL,
  "OFFER_ID" bigint NOT NULL,
  "ORDER_ITEM_ID" bigint DEFAULT NULL,
  PRIMARY KEY (ORDER_ITEM_ADJUSTMENT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order_item_attribute" (
  "ORDER_ITEM_ATTRIBUTE_ID" bigint NOT NULL,
  "NAME" varchar(255) NOT NULL,
  "VALUE" varchar(255) NOT NULL,
  "ORDER_ITEM_ID" bigint NOT NULL,
  PRIMARY KEY (ORDER_ITEM_ATTRIBUTE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order_item_cart_message" (
  "ORDER_ITEM_ID" bigint NOT NULL,
  "CART_MESSAGE" varchar(255) DEFAULT NULL
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order_item_dtl_adj" (
  "ORDER_ITEM_DTL_ADJ_ID" bigint NOT NULL,
  "APPLIED_TO_SALE_PRICE" bit(1) DEFAULT NULL,
  "OFFER_NAME" varchar(255) DEFAULT NULL,
  "ADJUSTMENT_REASON" varchar(255) NOT NULL,
  "ADJUSTMENT_VALUE" decimal(19,5) NOT NULL,
  "OFFER_ID" bigint NOT NULL,
  "ORDER_ITEM_PRICE_DTL_ID" bigint DEFAULT NULL,
  PRIMARY KEY (ORDER_ITEM_DTL_ADJ_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order_item_price_dtl" (
  "ORDER_ITEM_PRICE_DTL_ID" bigint NOT NULL,
  "QUANTITY" integer NOT NULL,
  "USE_SALE_PRICE" bit(1) DEFAULT NULL,
  "ORDER_ITEM_ID" bigint DEFAULT NULL,
  PRIMARY KEY (ORDER_ITEM_PRICE_DTL_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order_lock" (
  "LOCK_KEY" varchar(255) NOT NULL,
  "ORDER_ID" bigint NOT NULL,
  "LAST_UPDATED" bigint DEFAULT NULL,
  "LOCKED" char(1) DEFAULT NULL,
  PRIMARY KEY (LOCK_KEY,ORDER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order_multiship_option" (
  "ORDER_MULTISHIP_OPTION_ID" bigint NOT NULL,
  "ADDRESS_ID" bigint DEFAULT NULL,
  "FULFILLMENT_OPTION_ID" bigint DEFAULT NULL,
  "ORDER_ID" bigint DEFAULT NULL,
  "ORDER_ITEM_ID" bigint DEFAULT NULL,
  PRIMARY KEY (ORDER_MULTISHIP_OPTION_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order_offer_code_xref" (
  "ORDER_ID" bigint NOT NULL,
  "OFFER_CODE_ID" bigint NOT NULL
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order_payment" (
  "ORDER_PAYMENT_ID" bigint NOT NULL,
  "AMOUNT" decimal(19,5) DEFAULT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "GATEWAY_TYPE" varchar(255) DEFAULT NULL,
  "REFERENCE_NUMBER" varchar(255) DEFAULT NULL,
  "PAYMENT_TYPE" varchar(255) NOT NULL,
  "ADDRESS_ID" bigint DEFAULT NULL,
  "ORDER_ID" bigint DEFAULT NULL,
  PRIMARY KEY (ORDER_PAYMENT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_order_payment_transaction" (
  "PAYMENT_TRANSACTION_ID" bigint NOT NULL,
  "TRANSACTION_AMOUNT" decimal(19,2) DEFAULT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "CUSTOMER_IP_ADDRESS" varchar(255) DEFAULT NULL,
  "DATE_RECORDED" timestamp DEFAULT NULL,
  "RAW_RESPONSE" text,
  "SAVE_TOKEN" bit(1) DEFAULT NULL,
  "SUCCESS" bit(1) DEFAULT NULL,
  "TRANSACTION_TYPE" varchar(255) DEFAULT NULL,
  "ORDER_PAYMENT" bigint NOT NULL,
  "PARENT_TRANSACTION" bigint DEFAULT NULL,
  PRIMARY KEY (PAYMENT_TRANSACTION_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_page" (
  "PAGE_ID" bigint NOT NULL,
  "ACTIVE_END_DATE" timestamp DEFAULT NULL,
  "ACTIVE_START_DATE" timestamp DEFAULT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "DESCRIPTION" varchar(255) DEFAULT NULL,
  "EXCLUDE_FROM_SITE_MAP" bit(1) DEFAULT NULL,
  "FULL_URL" varchar(255) DEFAULT NULL,
  "META_DESCRIPTION" varchar(255) DEFAULT NULL,
  "META_TITLE" varchar(255) DEFAULT NULL,
  "OFFLINE_FLAG" bit(1) DEFAULT NULL,
  "PRIORITY" integer DEFAULT NULL,
  "PAGE_TMPLT_ID" bigint DEFAULT NULL,
  PRIMARY KEY (PAGE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_page_attributes" (
  "ATTRIBUTE_ID" bigint NOT NULL,
  "FIELD_NAME" varchar(255) NOT NULL,
  "FIELD_VALUE" varchar(255) DEFAULT NULL,
  "PAGE_ID" bigint NOT NULL,
  PRIMARY KEY (ATTRIBUTE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_page_fld" (
  "PAGE_FLD_ID" bigint NOT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "FLD_KEY" varchar(255) DEFAULT NULL,
  "LOB_VALUE" text,
  "VALUE" varchar(255) DEFAULT NULL,
  "PAGE_ID" bigint NOT NULL,
  PRIMARY KEY (PAGE_FLD_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_page_item_criteria" (
  "PAGE_ITEM_CRITERIA_ID" bigint NOT NULL,
  "ORDER_ITEM_MATCH_RULE" text,
  "QUANTITY" integer NOT NULL,
  PRIMARY KEY (PAGE_ITEM_CRITERIA_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_page_rule" (
  "PAGE_RULE_ID" bigint NOT NULL,
  "MATCH_RULE" text,
  PRIMARY KEY (PAGE_RULE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_page_rule_map" (
  "BLC_PAGE_PAGE_ID" bigint NOT NULL,
  "PAGE_RULE_ID" bigint NOT NULL,
  "MAP_KEY" varchar(255) NOT NULL,
  PRIMARY KEY (BLC_PAGE_PAGE_ID,MAP_KEY)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_page_tmplt" (
  "PAGE_TMPLT_ID" bigint NOT NULL,
  "TMPLT_DESCR" varchar(255) DEFAULT NULL,
  "TMPLT_NAME" varchar(255) DEFAULT NULL,
  "TMPLT_PATH" varchar(255) DEFAULT NULL,
  "LOCALE_CODE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (PAGE_TMPLT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_payment_log" (
  "PAYMENT_LOG_ID" bigint NOT NULL,
  "AMOUNT_PAID" decimal(19,5) DEFAULT NULL,
  "EXCEPTION_MESSAGE" varchar(255) DEFAULT NULL,
  "LOG_TYPE" varchar(255) NOT NULL,
  "ORDER_PAYMENT_ID" bigint DEFAULT NULL,
  "ORDER_PAYMENT_REF_NUM" varchar(255) DEFAULT NULL,
  "TRANSACTION_SUCCESS" bit(1) DEFAULT NULL,
  "TRANSACTION_TIMESTAMP" timestamp NOT NULL,
  "TRANSACTION_TYPE" varchar(255) NOT NULL,
  "USER_NAME" varchar(255) NOT NULL,
  "CURRENCY_CODE" varchar(255) DEFAULT NULL,
  "CUSTOMER_ID" bigint DEFAULT NULL,
  PRIMARY KEY (PAYMENT_LOG_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_personal_message" (
  "PERSONAL_MESSAGE_ID" bigint NOT NULL,
  "MESSAGE" varchar(255) DEFAULT NULL,
  "MESSAGE_FROM" varchar(255) DEFAULT NULL,
  "MESSAGE_TO" varchar(255) DEFAULT NULL,
  "OCCASION" varchar(255) DEFAULT NULL,
  PRIMARY KEY (PERSONAL_MESSAGE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_pgtmplt_fldgrp_xref" (
  "PG_TMPLT_FLD_GRP_ID" bigint NOT NULL,
  "GROUP_ORDER" decimal(10,6) DEFAULT NULL,
  "FLD_GROUP_ID" bigint DEFAULT NULL,
  "PAGE_TMPLT_ID" bigint DEFAULT NULL,
  PRIMARY KEY (PG_TMPLT_FLD_GRP_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_phone" (
  "PHONE_ID" bigint NOT NULL,
  "COUNTRY_CODE" varchar(255) DEFAULT NULL,
  "EXTENSION" varchar(255) DEFAULT NULL,
  "IS_ACTIVE" bit(1) DEFAULT NULL,
  "IS_DEFAULT" bit(1) DEFAULT NULL,
  "PHONE_NUMBER" varchar(255) NOT NULL,
  PRIMARY KEY (PHONE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_product" (
  "PRODUCT_ID" bigint NOT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "CAN_SELL_WITHOUT_OPTIONS" bit(1) DEFAULT NULL,
  "CANONICAL_URL" varchar(255) DEFAULT NULL,
  "DISPLAY_TEMPLATE" varchar(255) DEFAULT NULL,
  "IS_FEATURED_PRODUCT" bit(1) NOT NULL,
  "MANUFACTURE" varchar(255) DEFAULT NULL,
  "META_DESC" varchar(255) DEFAULT NULL,
  "META_TITLE" varchar(255) DEFAULT NULL,
  "MODEL" varchar(255) DEFAULT NULL,
  "OVERRIDE_GENERATED_URL" bit(1) DEFAULT NULL,
  "URL" varchar(255) DEFAULT NULL,
  "URL_KEY" varchar(255) DEFAULT NULL,
  "DEFAULT_CATEGORY_ID" bigint DEFAULT NULL,
  "DEFAULT_SKU_ID" bigint DEFAULT NULL,
  PRIMARY KEY (PRODUCT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_product_attribute" (
  "PRODUCT_ATTRIBUTE_ID" bigint NOT NULL,
  "NAME" varchar(255) NOT NULL,
  "VALUE" varchar(255) DEFAULT NULL,
  "PRODUCT_ID" bigint NOT NULL,
  PRIMARY KEY (PRODUCT_ATTRIBUTE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_product_bundle" (
  "AUTO_BUNDLE" bit(1) DEFAULT NULL,
  "BUNDLE_PROMOTABLE" bit(1) DEFAULT NULL,
  "ITEMS_PROMOTABLE" bit(1) DEFAULT NULL,
  "PRICING_MODEL" varchar(255) DEFAULT NULL,
  "BUNDLE_PRIORITY" integer DEFAULT NULL,
  "PRODUCT_ID" bigint NOT NULL,
  PRIMARY KEY (PRODUCT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_product_cross_sale" (
  "CROSS_SALE_PRODUCT_ID" bigint NOT NULL,
  "PROMOTION_MESSAGE" varchar(255) DEFAULT NULL,
  "SEQUENCE" decimal(10,6) DEFAULT NULL,
  "CATEGORY_ID" bigint DEFAULT NULL,
  "PRODUCT_ID" bigint DEFAULT NULL,
  "RELATED_SALE_PRODUCT_ID" bigint NOT NULL,
  PRIMARY KEY (CROSS_SALE_PRODUCT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_product_featured" (
  "FEATURED_PRODUCT_ID" bigint NOT NULL,
  "PROMOTION_MESSAGE" varchar(255) DEFAULT NULL,
  "SEQUENCE" decimal(10,6) DEFAULT NULL,
  "CATEGORY_ID" bigint DEFAULT NULL,
  "PRODUCT_ID" bigint DEFAULT NULL,
  PRIMARY KEY (FEATURED_PRODUCT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_product_option" (
  "PRODUCT_OPTION_ID" bigint NOT NULL,
  "ATTRIBUTE_NAME" varchar(255) DEFAULT NULL,
  "DISPLAY_ORDER" integer DEFAULT NULL,
  "ERROR_CODE" varchar(255) DEFAULT NULL,
  "ERROR_MESSAGE" varchar(255) DEFAULT NULL,
  "LABEL" varchar(255) DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  "VALIDATION_STRATEGY_TYPE" varchar(255) DEFAULT NULL,
  "VALIDATION_TYPE" varchar(255) DEFAULT NULL,
  "REQUIRED" bit(1) DEFAULT NULL,
  "OPTION_TYPE" varchar(255) DEFAULT NULL,
  "USE_IN_SKU_GENERATION" bit(1) DEFAULT NULL,
  "VALIDATION_STRING" varchar(255) DEFAULT NULL,
  PRIMARY KEY (PRODUCT_OPTION_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_product_option_value" (
  "PRODUCT_OPTION_VALUE_ID" bigint NOT NULL,
  "ATTRIBUTE_VALUE" varchar(255) DEFAULT NULL,
  "DISPLAY_ORDER" bigint DEFAULT NULL,
  "PRICE_ADJUSTMENT" decimal(19,5) DEFAULT NULL,
  "PRODUCT_OPTION_ID" bigint DEFAULT NULL,
  PRIMARY KEY (PRODUCT_OPTION_VALUE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_product_option_xref" (
  "PRODUCT_OPTION_XREF_ID" bigint NOT NULL,
  "PRODUCT_ID" bigint NOT NULL,
  "PRODUCT_OPTION_ID" bigint NOT NULL,
  PRIMARY KEY (PRODUCT_OPTION_XREF_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_product_up_sale" (
  "UP_SALE_PRODUCT_ID" bigint NOT NULL,
  "PROMOTION_MESSAGE" varchar(255) DEFAULT NULL,
  "SEQUENCE" decimal(10,6) DEFAULT NULL,
  "CATEGORY_ID" bigint DEFAULT NULL,
  "PRODUCT_ID" bigint DEFAULT NULL,
  "RELATED_SALE_PRODUCT_ID" bigint DEFAULT NULL,
  PRIMARY KEY (UP_SALE_PRODUCT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_promotion_message" (
  "PROMOTION_MESSAGE_ID" bigint NOT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "END_DATE" timestamp DEFAULT NULL,
  "PROMOTION_MESSASGE" varchar(255) DEFAULT NULL,
  "MESSAGE_PLACEMENT" varchar(255) DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  "PROMOTION_MESSAGE_PRIORITY" integer DEFAULT NULL,
  "START_DATE" timestamp DEFAULT NULL,
  "LOCALE_CODE" varchar(255) DEFAULT NULL,
  "MEDIA_ID" bigint DEFAULT NULL,
  PRIMARY KEY (PROMOTION_MESSAGE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_prorated_order_item_adjust" (
  "PRORATED_ORDER_ITEM_ADJUST_ID" bigint NOT NULL,
  "PRORATED_QUANTITY" integer NOT NULL,
  "ADJUSTMENT_REASON" varchar(255) NOT NULL,
  "PRORATED_ADJUSTMENT_VALUE" decimal(19,5) NOT NULL,
  "OFFER_ID" bigint NOT NULL,
  "ORDER_ITEM_ID" bigint DEFAULT NULL,
  PRIMARY KEY (PRORATED_ORDER_ITEM_ADJUST_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_qual_crit_offer_xref" (
  "OFFER_QUAL_CRIT_ID" bigint NOT NULL,
  "OFFER_ID" bigint NOT NULL,
  "OFFER_ITEM_CRITERIA_ID" bigint DEFAULT NULL,
  PRIMARY KEY (OFFER_QUAL_CRIT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_qual_crit_page_xref" (
  "PAGE_ID" bigint NOT NULL,
  "PAGE_ITEM_CRITERIA_ID" bigint NOT NULL,
  PRIMARY KEY (PAGE_ID,PAGE_ITEM_CRITERIA_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_qual_crit_sc_xref" (
  "SC_ID" bigint NOT NULL,
  "SC_ITEM_CRITERIA_ID" bigint NOT NULL,
  PRIMARY KEY (SC_ID,SC_ITEM_CRITERIA_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_rating_detail" (
  "RATING_DETAIL_ID" bigint NOT NULL,
  "RATING" double precision NOT NULL,
  "RATING_SUBMITTED_DATE" timestamp NOT NULL,
  "CUSTOMER_ID" bigint NOT NULL,
  "RATING_SUMMARY_ID" bigint NOT NULL,
  PRIMARY KEY (RATING_DETAIL_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_rating_summary" (
  "RATING_SUMMARY_ID" bigint NOT NULL,
  "AVERAGE_RATING" double precision NOT NULL,
  "ITEM_ID" varchar(255) NOT NULL,
  "RATING_TYPE" varchar(255) NOT NULL,
  PRIMARY KEY (RATING_SUMMARY_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_review_detail" (
  "REVIEW_DETAIL_ID" bigint NOT NULL,
  "HELPFUL_COUNT" integer NOT NULL,
  "NOT_HELPFUL_COUNT" integer NOT NULL,
  "REVIEW_SUBMITTED_DATE" timestamp NOT NULL,
  "REVIEW_STATUS" varchar(255) NOT NULL,
  "REVIEW_TEXT" varchar(255) NOT NULL,
  "CUSTOMER_ID" bigint NOT NULL,
  "RATING_DETAIL_ID" bigint DEFAULT NULL,
  "RATING_SUMMARY_ID" bigint NOT NULL,
  PRIMARY KEY (REVIEW_DETAIL_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_review_feedback" (
  "REVIEW_FEEDBACK_ID" bigint NOT NULL,
  "IS_HELPFUL" bit(1) NOT NULL,
  "CUSTOMER_ID" bigint NOT NULL,
  "REVIEW_DETAIL_ID" bigint NOT NULL,
  PRIMARY KEY (REVIEW_FEEDBACK_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_role" (
  "ROLE_ID" bigint NOT NULL,
  "ROLE_NAME" varchar(255) NOT NULL,
  PRIMARY KEY (ROLE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sandbox" (
  "SANDBOX_ID" bigint NOT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "AUTHOR" bigint DEFAULT NULL,
  "COLOR" varchar(255) DEFAULT NULL,
  "DESCRIPTION" varchar(255) DEFAULT NULL,
  "GO_LIVE_DATE" timestamp DEFAULT NULL,
  "SANDBOX_NAME" varchar(255) DEFAULT NULL,
  "SANDBOX_TYPE" varchar(255) DEFAULT NULL,
  "PARENT_SANDBOX_ID" bigint DEFAULT NULL,
  PRIMARY KEY (SANDBOX_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sandbox_mgmt" (
  "SANDBOX_MGMT_ID" bigint NOT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "SANDBOX_ID" bigint NOT NULL,
  PRIMARY KEY (SANDBOX_MGMT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sc" (
  "SC_ID" bigint NOT NULL,
  "CONTENT_NAME" varchar(255) NOT NULL,
  "OFFLINE_FLAG" bit(1) DEFAULT NULL,
  "PRIORITY" integer NOT NULL,
  "LOCALE_CODE" varchar(255) NOT NULL,
  "SC_TYPE_ID" bigint DEFAULT NULL,
  PRIMARY KEY (SC_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sc_fld" (
  "SC_FLD_ID" bigint NOT NULL,
  "FLD_KEY" varchar(255) DEFAULT NULL,
  "LOB_VALUE" text,
  "VALUE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (SC_FLD_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sc_fld_map" (
  "BLC_SC_SC_FIELD_ID" bigint NOT NULL,
  "MAP_KEY" varchar(255) NOT NULL,
  "SC_ID" bigint NOT NULL,
  "SC_FLD_ID" bigint DEFAULT NULL,
  PRIMARY KEY (BLC_SC_SC_FIELD_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sc_fld_tmplt" (
  "SC_FLD_TMPLT_ID" bigint NOT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  PRIMARY KEY (SC_FLD_TMPLT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sc_fldgrp_xref" (
  "BLC_SC_FLDGRP_XREF_ID" bigint NOT NULL,
  "GROUP_ORDER" integer DEFAULT NULL,
  "FLD_GROUP_ID" bigint DEFAULT NULL,
  "SC_FLD_TMPLT_ID" bigint DEFAULT NULL,
  PRIMARY KEY (BLC_SC_FLDGRP_XREF_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sc_item_criteria" (
  "SC_ITEM_CRITERIA_ID" bigint NOT NULL,
  "ORDER_ITEM_MATCH_RULE" text,
  "QUANTITY" integer NOT NULL,
  "SC_ID" bigint DEFAULT NULL,
  PRIMARY KEY (SC_ITEM_CRITERIA_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sc_rule" (
  "SC_RULE_ID" bigint NOT NULL,
  "MATCH_RULE" text,
  PRIMARY KEY (SC_RULE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sc_rule_map" (
  "BLC_SC_SC_ID" bigint NOT NULL,
  "SC_RULE_ID" bigint NOT NULL,
  "MAP_KEY" varchar(255) NOT NULL,
  PRIMARY KEY (BLC_SC_SC_ID,MAP_KEY)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sc_type" (
  "SC_TYPE_ID" bigint NOT NULL,
  "DESCRIPTION" varchar(255) DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  "SC_FLD_TMPLT_ID" bigint DEFAULT NULL,
  PRIMARY KEY (SC_TYPE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_search_facet" (
  "SEARCH_FACET_ID" bigint NOT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "MULTISELECT" bit(1) DEFAULT NULL,
  "LABEL" varchar(255) DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  "REQUIRES_ALL_DEPENDENT" bit(1) DEFAULT NULL,
  "SEARCH_DISPLAY_PRIORITY" integer DEFAULT NULL,
  "SHOW_ON_SEARCH" bit(1) DEFAULT NULL,
  "USE_FACET_RANGES" bit(1) DEFAULT NULL,
  PRIMARY KEY (SEARCH_FACET_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_search_facet_range" (
  "SEARCH_FACET_RANGE_ID" bigint NOT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "MAX_VALUE" decimal(19,5) DEFAULT NULL,
  "MIN_VALUE" decimal(19,5) NOT NULL,
  "SEARCH_FACET_ID" bigint DEFAULT NULL,
  PRIMARY KEY (SEARCH_FACET_RANGE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_search_facet_xref" (
  "ID" bigint NOT NULL,
  "REQUIRED_FACET_ID" bigint NOT NULL,
  "SEARCH_FACET_ID" bigint NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_search_intercept" (
  "SEARCH_REDIRECT_ID" bigint NOT NULL,
  "ACTIVE_END_DATE" timestamp DEFAULT NULL,
  "ACTIVE_START_DATE" timestamp DEFAULT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "PRIORITY" integer DEFAULT NULL,
  "SEARCH_TERM" varchar(255) NOT NULL,
  "URL" varchar(255) NOT NULL,
  PRIMARY KEY (SEARCH_REDIRECT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_search_synonym" (
  "SEARCH_SYNONYM_ID" bigint NOT NULL,
  "SYNONYMS" varchar(255) DEFAULT NULL,
  "TERM" varchar(255) DEFAULT NULL,
  PRIMARY KEY (SEARCH_SYNONYM_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_shipping_rate" (
  "ID" bigint NOT NULL,
  "BAND_RESULT_PCT" integer NOT NULL,
  "BAND_RESULT_QTY" decimal(19,2) NOT NULL,
  "BAND_UNIT_QTY" decimal(19,2) NOT NULL,
  "FEE_BAND" integer NOT NULL,
  "FEE_SUB_TYPE" varchar(255) DEFAULT NULL,
  "FEE_TYPE" varchar(255) NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_site" (
  "SITE_ID" bigint NOT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "DEACTIVATED" bit(1) DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  "SITE_IDENTIFIER_TYPE" varchar(255) DEFAULT NULL,
  "SITE_IDENTIFIER_VALUE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (SITE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_site_catalog" (
  "SITE_CATALOG_XREF_ID" bigint NOT NULL,
  "CATALOG_ID" bigint NOT NULL,
  "SITE_ID" bigint NOT NULL,
  PRIMARY KEY (SITE_CATALOG_XREF_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_site_map_cfg" (
  "MAX_URL_ENTRIES_PER_FILE" integer DEFAULT NULL,
  "SITE_MAP_FILE_NAME" varchar(255) DEFAULT NULL,
  "MODULE_CONFIG_ID" bigint NOT NULL,
  PRIMARY KEY (MODULE_CONFIG_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_site_map_gen_cfg" (
  "GEN_CONFIG_ID" bigint NOT NULL,
  "CHANGE_FREQ" varchar(255) NOT NULL,
  "DISABLED" bit(1) NOT NULL,
  "GENERATOR_TYPE" varchar(255) NOT NULL,
  "PRIORITY" varchar(255) DEFAULT NULL,
  "MODULE_CONFIG_ID" bigint NOT NULL,
  PRIMARY KEY (GEN_CONFIG_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_site_map_url_entry" (
  "URL_ENTRY_ID" bigint NOT NULL,
  "CHANGE_FREQ" varchar(255) NOT NULL,
  "LAST_MODIFIED" timestamp NOT NULL,
  "LOCATION" varchar(255) NOT NULL,
  "PRIORITY" varchar(255) NOT NULL,
  "GEN_CONFIG_ID" bigint NOT NULL,
  PRIMARY KEY (URL_ENTRY_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sku" (
  "SKU_ID" bigint NOT NULL,
  "ACTIVE_END_DATE" timestamp DEFAULT NULL,
  "ACTIVE_START_DATE" timestamp DEFAULT NULL,
  "AVAILABLE_FLAG" char(1) DEFAULT NULL,
  "COST" decimal(19,5) DEFAULT NULL,
  "DESCRIPTION" varchar(255) DEFAULT NULL,
  "CONTAINER_SHAPE" varchar(255) DEFAULT NULL,
  "DEPTH" decimal(19,2) DEFAULT NULL,
  "DIMENSION_UNIT_OF_MEASURE" varchar(255) DEFAULT NULL,
  "GIRTH" decimal(19,2) DEFAULT NULL,
  "HEIGHT" decimal(19,2) DEFAULT NULL,
  "CONTAINER_SIZE" varchar(255) DEFAULT NULL,
  "WIDTH" decimal(19,2) DEFAULT NULL,
  "DISCOUNTABLE_FLAG" char(1) DEFAULT NULL,
  "DISPLAY_TEMPLATE" varchar(255) DEFAULT NULL,
  "EXTERNAL_ID" varchar(255) DEFAULT NULL,
  "FULFILLMENT_TYPE" varchar(255) DEFAULT NULL,
  "INVENTORY_TYPE" varchar(255) DEFAULT NULL,
  "IS_MACHINE_SORTABLE" bit(1) DEFAULT NULL,
  "LONG_DESCRIPTION" text,
  "NAME" varchar(255) DEFAULT NULL,
  "QUANTITY_AVAILABLE" integer DEFAULT NULL,
  "RETAIL_PRICE" decimal(19,5) DEFAULT NULL,
  "SALE_PRICE" decimal(19,5) DEFAULT NULL,
  "TAX_CODE" varchar(255) DEFAULT NULL,
  "TAXABLE_FLAG" char(1) DEFAULT NULL,
  "UPC" varchar(255) DEFAULT NULL,
  "URL_KEY" varchar(255) DEFAULT NULL,
  "WEIGHT" decimal(19,2) DEFAULT NULL,
  "WEIGHT_UNIT_OF_MEASURE" varchar(255) DEFAULT NULL,
  "CURRENCY_CODE" varchar(255) DEFAULT NULL,
  "DEFAULT_PRODUCT_ID" bigint DEFAULT NULL,
  "ADDL_PRODUCT_ID" bigint DEFAULT NULL,
  PRIMARY KEY (SKU_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sku_attribute" (
  "SKU_ATTR_ID" bigint NOT NULL,
  "NAME" varchar(255) NOT NULL,
  "VALUE" varchar(255) NOT NULL,
  "SKU_ID" bigint NOT NULL,
  PRIMARY KEY (SKU_ATTR_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sku_availability" (
  "SKU_AVAILABILITY_ID" bigint NOT NULL,
  "AVAILABILITY_DATE" timestamp DEFAULT NULL,
  "AVAILABILITY_STATUS" varchar(255) DEFAULT NULL,
  "LOCATION_ID" bigint DEFAULT NULL,
  "QTY_ON_HAND" integer DEFAULT NULL,
  "RESERVE_QTY" integer DEFAULT NULL,
  "SKU_ID" bigint DEFAULT NULL,
  PRIMARY KEY (SKU_AVAILABILITY_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sku_bundle_item" (
  "SKU_BUNDLE_ITEM_ID" bigint NOT NULL,
  "ITEM_SALE_PRICE" decimal(19,5) DEFAULT NULL,
  "QUANTITY" integer NOT NULL,
  "SEQUENCE" decimal(10,6) DEFAULT NULL,
  "PRODUCT_BUNDLE_ID" bigint NOT NULL,
  "SKU_ID" bigint NOT NULL,
  PRIMARY KEY (SKU_BUNDLE_ITEM_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sku_fee" (
  "SKU_FEE_ID" bigint NOT NULL,
  "AMOUNT" decimal(19,5) NOT NULL,
  "DESCRIPTION" varchar(255) DEFAULT NULL,
  "EXPRESSION" text,
  "FEE_TYPE" varchar(255) DEFAULT NULL,
  "NAME" varchar(255) DEFAULT NULL,
  "TAXABLE" bit(1) DEFAULT NULL,
  "CURRENCY_CODE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (SKU_FEE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sku_fee_xref" (
  "SKU_FEE_ID" bigint NOT NULL,
  "SKU_ID" bigint NOT NULL
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sku_fulfillment_excluded" (
  "SKU_ID" bigint NOT NULL,
  "FULFILLMENT_OPTION_ID" bigint NOT NULL
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sku_fulfillment_flat_rates" (
  "SKU_ID" bigint NOT NULL,
  "RATE" decimal(19,5) DEFAULT NULL,
  "FULFILLMENT_OPTION_ID" bigint NOT NULL,
  PRIMARY KEY (SKU_ID,FULFILLMENT_OPTION_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sku_media_map" (
  "SKU_MEDIA_ID" bigint NOT NULL,
  "MAP_KEY" varchar(255) NOT NULL,
  "MEDIA_ID" bigint DEFAULT NULL,
  "BLC_SKU_SKU_ID" bigint NOT NULL,
  PRIMARY KEY (SKU_MEDIA_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_sku_option_value_xref" (
  "SKU_OPTION_VALUE_XREF_ID" bigint NOT NULL,
  "PRODUCT_OPTION_VALUE_ID" bigint NOT NULL,
  "SKU_ID" bigint NOT NULL,
  PRIMARY KEY (SKU_OPTION_VALUE_XREF_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_state" (
  "ABBREVIATION" varchar(255) NOT NULL,
  "NAME" varchar(255) NOT NULL,
  "COUNTRY" varchar(255) NOT NULL,
  PRIMARY KEY (ABBREVIATION)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_static_asset" (
  "STATIC_ASSET_ID" bigint NOT NULL,
  "ALT_TEXT" varchar(255) DEFAULT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "FILE_EXTENSION" varchar(255) DEFAULT NULL,
  "FILE_SIZE" bigint DEFAULT NULL,
  "FULL_URL" varchar(255) NOT NULL,
  "MIME_TYPE" varchar(255) DEFAULT NULL,
  "NAME" varchar(255) NOT NULL,
  "STORAGE_TYPE" varchar(255) DEFAULT NULL,
  "TITLE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (STATIC_ASSET_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_static_asset_desc" (
  "STATIC_ASSET_DESC_ID" bigint NOT NULL,
  "CREATED_BY" bigint DEFAULT NULL,
  "DATE_CREATED" timestamp DEFAULT NULL,
  "DATE_UPDATED" timestamp DEFAULT NULL,
  "UPDATED_BY" bigint DEFAULT NULL,
  "DESCRIPTION" varchar(255) DEFAULT NULL,
  "LONG_DESCRIPTION" varchar(255) DEFAULT NULL,
  PRIMARY KEY (STATIC_ASSET_DESC_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_static_asset_strg" (
  "STATIC_ASSET_STRG_ID" bigint NOT NULL,
  "FILE_DATA" bytea,
  "STATIC_ASSET_ID" bigint NOT NULL,
  PRIMARY KEY (STATIC_ASSET_STRG_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_store" (
  "STORE_ID" bigint NOT NULL,
  "ARCHIVED" char(1) DEFAULT NULL,
  "LATITUDE" double precision DEFAULT NULL,
  "LONGITUDE" double precision DEFAULT NULL,
  "STORE_NAME" varchar(255) NOT NULL,
  "STORE_OPEN" bit(1) DEFAULT NULL,
  "STORE_HOURS" varchar(255) DEFAULT NULL,
  "STORE_NUMBER" varchar(255) DEFAULT NULL,
  "ADDRESS_ID" bigint DEFAULT NULL,
  PRIMARY KEY (STORE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_system_property" (
  "BLC_SYSTEM_PROPERTY_ID" bigint NOT NULL,
  "FRIENDLY_GROUP" varchar(255) DEFAULT NULL,
  "FRIENDLY_NAME" varchar(255) DEFAULT NULL,
  "FRIENDLY_TAB" varchar(255) DEFAULT NULL,
  "PROPERTY_NAME" varchar(255) NOT NULL,
  "OVERRIDE_GENERATED_PROP_NAME" bit(1) DEFAULT NULL,
  "PROPERTY_TYPE" varchar(255) DEFAULT NULL,
  "PROPERTY_VALUE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (BLC_SYSTEM_PROPERTY_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_tar_crit_offer_xref" (
  "OFFER_TAR_CRIT_ID" bigint NOT NULL,
  "OFFER_ID" bigint NOT NULL,
  "OFFER_ITEM_CRITERIA_ID" bigint DEFAULT NULL,
  PRIMARY KEY (OFFER_TAR_CRIT_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_tax_detail" (
  "TAX_DETAIL_ID" bigint NOT NULL,
  "AMOUNT" decimal(19,5) DEFAULT NULL,
  "TAX_COUNTRY" varchar(255) DEFAULT NULL,
  "JURISDICTION_NAME" varchar(255) DEFAULT NULL,
  "RATE" decimal(19,5) DEFAULT NULL,
  "TAX_REGION" varchar(255) DEFAULT NULL,
  "TAX_NAME" varchar(255) DEFAULT NULL,
  "TYPE" varchar(255) DEFAULT NULL,
  "CURRENCY_CODE" varchar(255) DEFAULT NULL,
  "MODULE_CONFIG_ID" bigint DEFAULT NULL,
  PRIMARY KEY (TAX_DETAIL_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_trans_additnl_fields" (
  "PAYMENT_TRANSACTION_ID" bigint NOT NULL,
  "FIELD_VALUE" text,
  "FIELD_NAME" varchar(255) NOT NULL,
  PRIMARY KEY (PAYMENT_TRANSACTION_ID,FIELD_NAME)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_translation" (
  "TRANSLATION_ID" bigint NOT NULL,
  "ENTITY_ID" varchar(255) DEFAULT NULL,
  "ENTITY_TYPE" varchar(255) DEFAULT NULL,
  "FIELD_NAME" varchar(255) DEFAULT NULL,
  "LOCALE_CODE" varchar(255) DEFAULT NULL,
  "TRANSLATED_VALUE" text,
  PRIMARY KEY (TRANSLATION_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_url_handler" (
  "URL_HANDLER_ID" bigint NOT NULL,
  "INCOMING_URL" varchar(255) NOT NULL,
  "IS_REGEX" bit(1) DEFAULT NULL,
  "NEW_URL" varchar(255) NOT NULL,
  "URL_REDIRECT_TYPE" varchar(255) DEFAULT NULL,
  PRIMARY KEY (URL_HANDLER_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_userconnection" (
  "providerId" varchar(255) NOT NULL,
  "providerUserId" varchar(255) NOT NULL,
  "userId" varchar(255) NOT NULL,
  "accessToken" varchar(255) NOT NULL,
  "displayName" varchar(255) DEFAULT NULL,
  "expireTime" bigint DEFAULT NULL,
  "imageUrl" varchar(255) DEFAULT NULL,
  "profileUrl" varchar(255) DEFAULT NULL,
  "rank" integer NOT NULL,
  "refreshToken" varchar(255) DEFAULT NULL,
  "secret" varchar(255) DEFAULT NULL,
  PRIMARY KEY (providerId,providerUserId,userId)
);


CREATE TABLE IF NOT EXISTS broadleaf."blc_zip_code" (
  "ZIP_CODE_ID" varchar(255) NOT NULL,
  "ZIP_CITY" varchar(255) DEFAULT NULL,
  "ZIP_LATITUDE" double precision DEFAULT NULL,
  "ZIP_LONGITUDE" double precision DEFAULT NULL,
  "ZIP_STATE" varchar(255) DEFAULT NULL,
  "ZIPCODE" integer DEFAULT NULL,
  PRIMARY KEY (ZIP_CODE_ID)
);


CREATE TABLE IF NOT EXISTS broadleaf."sequence_generator" (
  "ID_NAME" varchar(255) NOT NULL,
  "ID_VAL" bigint DEFAULT NULL,
  PRIMARY KEY (ID_NAME)
);

